import { Router } from "express";
import { authMiddleware } from "../middleware/auth.js";
import { requireAdmin } from "../middleware/adminAuth.js";
import { createAdminConsoleRouter } from "../modules/adminConsole/index.js";
import { createAdminCommunityRouter } from "../modules/adminCommunity/index.js";
import { createAdminFoodAssetsRouter } from "../modules/adminFoodAssets/index.js";
import { createAdminKitchenwareRouter } from "../modules/adminKitchenware/index.js";
import { createAdminRecipesRouter } from "../modules/adminRecipes/index.js";
import { createAdminUsersRouter } from "../modules/adminUsers/index.js";
import { createAdminVoicePackRouter } from "../modules/voicePacks/index.js";
import { createAdminWorkerRunsRouter } from "../modules/worker/index.js";
import { createAdminAgentRunsRouter } from "./admin/agent-runs.js";
import { createAdminAIConfigRouter } from "./admin/ai-config.js";
import { createAdminMediaCleanupRouter } from "./admin/media-cleanup.js";
import { createAdminNotificationsRouter } from "./admin/notifications.js";

const router = Router();
router.use(authMiddleware);
router.use(requireAdmin);
router.use(createAdminAIConfigRouter());
router.use(createAdminUsersRouter());
router.use(createAdminCommunityRouter());
router.use(createAdminRecipesRouter());
router.use(createAdminKitchenwareRouter());
router.use(createAdminFoodAssetsRouter());
router.use(createAdminNotificationsRouter());
router.use(createAdminAgentRunsRouter());
router.use(createAdminMediaCleanupRouter());
router.use(createAdminVoicePackRouter());
router.use(createAdminWorkerRunsRouter());
router.use(createAdminConsoleRouter());

export default router;
