import type{Pool}from"pg";import type{StoredMediaReference}from"../../services/mediaStorage.js";import type{MediaCleanupRepository}from"./repository.js";import type{MediaCleanupJob,MediaCleanupJobRow,MediaCleanupListQuery}from"./types.js";
export class PostgresMediaCleanupRepository implements MediaCleanupRepository{private readonly pool:Pool;constructor(pool:Pool){this.pool=pool;}
 async enqueue(userId:number,urls:string[],objects:StoredMediaReference[]){return Number((await this.pool.query("INSERT INTO media_cleanup_jobs(owner_user_id,urls_json,objects_json)VALUES($1,$2::jsonb,$3::jsonb)RETURNING id",[userId,JSON.stringify(urls),JSON.stringify(objects)])).rows[0].id);}
 async claim(id:number,token:string,minutes:number){const r=await this.pool.query(`UPDATE media_cleanup_jobs SET status='processing',attempts=attempts+1,last_error=NULL,claim_token=$1,claimed_at=NOW(),updated_at=NOW() WHERE id=$2 AND(status='pending' OR(status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-($3*INTERVAL '1 minute')))RETURNING *`,[token,id,minutes]);return(r.rows[0]as MediaCleanupJob|undefined)||null;}
 async complete(id:number,token:string){return(await this.pool.query(`UPDATE media_cleanup_jobs SET status='completed',last_error=NULL,claim_token=NULL,claimed_at=NULL,updated_at=NOW(),completed_at=NOW() WHERE id=$1 AND status='processing' AND claim_token=$2`,[id,token])).rowCount===1;}
 async release(id:number,token:string,error:string){await this.pool.query(`UPDATE media_cleanup_jobs SET status='pending',last_error=$1,claim_token=NULL,claimed_at=NULL,updated_at=NOW() WHERE id=$2 AND status='processing' AND claim_token=$3`,[error,id,token]);}
 async pending(limit:number,minutes:number){return(await this.pool.query(`SELECT id FROM media_cleanup_jobs WHERE status='pending' OR(status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-($1*INTERVAL '1 minute'))ORDER BY created_at,id LIMIT $2`,[minutes,limit])).rows.map(r=>Number(r.id));}
 async job(id:number,minutes:number){return((await this.pool.query(`SELECT *,EXTRACT(EPOCH FROM(NOW()-created_at))age_seconds,(status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-($1*INTERVAL '1 minute'))is_stale FROM media_cleanup_jobs WHERE id=$2`,[minutes,id])).rows[0]as MediaCleanupJobRow|undefined)||null;}
 async list(q:MediaCleanupListQuery){const params:Array<string|number>=[],p=(v:string|number)=>{params.push(v);return`$${params.length}`;};const conditions:string[]=[];
  if(["pending","processing","completed"].includes(q.status))conditions.push(`status=${p(q.status)}`);else if(q.status==="attention")conditions.push("status IN ('pending','processing')");else if(q.status==="failing")conditions.push("status='pending' AND attempts>=3");else if(q.status==="stale")conditions.push(`status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-(${p(q.staleMinutes)}*INTERVAL '1 minute')`);if(q.olderThanHours>0)conditions.push(`created_at<=NOW()-(${p(q.olderThanHours)}*INTERVAL '1 hour')`);const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:"";
  const total=Number((await this.pool.query(`SELECT COUNT(*) count FROM media_cleanup_jobs ${where}`,params)).rows[0].count);const staleParam=p(q.staleMinutes),limit=p(q.pageSize),offset=p((q.page-1)*q.pageSize);
  const rows=(await this.pool.query(`SELECT *,EXTRACT(EPOCH FROM(NOW()-created_at))age_seconds,(status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-(${staleParam}*INTERVAL '1 minute'))is_stale FROM media_cleanup_jobs ${where} ORDER BY CASE WHEN status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-(${staleParam}*INTERVAL '1 minute')THEN 0 WHEN status='pending' AND attempts>=3 THEN 1 WHEN status='pending'THEN 2 WHEN status='processing'THEN 3 ELSE 4 END,created_at,id LIMIT ${limit} OFFSET ${offset}`,params)).rows as MediaCleanupJobRow[];
  const raw=(await this.pool.query(`SELECT COUNT(*)FILTER(WHERE status='pending')pending,COUNT(*)FILTER(WHERE status='processing')processing,COUNT(*)FILTER(WHERE status='completed')completed,COUNT(*)FILTER(WHERE status='pending' AND attempts>=3)failing,COUNT(*)FILTER(WHERE status='processing' AND COALESCE(claimed_at,updated_at)<=NOW()-($1*INTERVAL '1 minute'))stale FROM media_cleanup_jobs`,[q.staleMinutes])).rows[0];return{rows,total,summary:Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Number(v)||0]))};}}
