import type Database from "better-sqlite3";import type{StoredMediaReference}from"../../services/mediaStorage.js";
import type{MediaCleanupRepository}from"./repository.js";import type{MediaCleanupJob,MediaCleanupJobRow,MediaCleanupListQuery}from"./types.js";
const stale=(minutes:number)=>`-${Math.max(1,Math.min(Math.floor(minutes),1440))} minutes`;
export class SqliteMediaCleanupRepository implements MediaCleanupRepository{private readonly database:Database.Database;constructor(database:Database.Database){this.database=database;}
 async enqueue(userId:number,urls:string[],objects:StoredMediaReference[]){const r=this.database.prepare("INSERT INTO media_cleanup_jobs(owner_user_id,urls_json,objects_json)VALUES(?,?,?)").run(userId,JSON.stringify(urls),JSON.stringify(objects));return Number(r.lastInsertRowid);}
 async claim(id:number,token:string,minutes:number){const changed=this.database.prepare(`UPDATE media_cleanup_jobs SET status='processing',attempts=attempts+1,last_error=NULL,claim_token=?,claimed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND(status='pending' OR(status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?)))`).run(token,id,stale(minutes));if(!changed.changes)return null;return(this.database.prepare("SELECT * FROM media_cleanup_jobs WHERE id=? AND claim_token=?").get(id,token)as MediaCleanupJob|undefined)||null;}
 async complete(id:number,token:string){return this.database.prepare(`UPDATE media_cleanup_jobs SET status='completed',last_error=NULL,claim_token=NULL,claimed_at=NULL,updated_at=CURRENT_TIMESTAMP,completed_at=CURRENT_TIMESTAMP WHERE id=? AND status='processing' AND claim_token=?`).run(id,token).changes>0;}
 async release(id:number,token:string,error:string){this.database.prepare(`UPDATE media_cleanup_jobs SET status='pending',last_error=?,claim_token=NULL,claimed_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='processing' AND claim_token=?`).run(error,id,token);}
 async pending(limit:number,minutes:number){return(this.database.prepare(`SELECT id FROM media_cleanup_jobs WHERE status='pending' OR(status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?))ORDER BY created_at,id LIMIT ?`).all(stale(minutes),limit)as Array<{id:number}>).map(r=>r.id);}
 async job(id:number,minutes:number){return(this.database.prepare(`SELECT *,ROUND((julianday('now')-julianday(created_at))*86400)age_seconds,CASE WHEN status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?)THEN 1 ELSE 0 END is_stale FROM media_cleanup_jobs WHERE id=?`).get(stale(minutes),id)as MediaCleanupJobRow|undefined)||null;}
 async list(q:MediaCleanupListQuery){const conditions:string[]=[],params:Array<string|number>=[];if(["pending","processing","completed"].includes(q.status)){conditions.push("status=?");params.push(q.status);}else if(q.status==="attention")conditions.push("status IN ('pending','processing')");else if(q.status==="failing")conditions.push("status='pending' AND attempts>=3");else if(q.status==="stale"){conditions.push("status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?)");params.push(stale(q.staleMinutes));}if(q.olderThanHours>0){conditions.push("created_at<=datetime('now',?)");params.push(`-${q.olderThanHours} hours`);}const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:"";
  const total=Number((this.database.prepare(`SELECT COUNT(*) count FROM media_cleanup_jobs ${where}`).get(...params)as{id:number;count:number}).count);const s=stale(q.staleMinutes);
  const rows=this.database.prepare(`SELECT *,ROUND((julianday('now')-julianday(created_at))*86400)age_seconds,CASE WHEN status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?)THEN 1 ELSE 0 END is_stale FROM media_cleanup_jobs ${where} ORDER BY CASE WHEN status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?)THEN 0 WHEN status='pending' AND attempts>=3 THEN 1 WHEN status='pending'THEN 2 WHEN status='processing'THEN 3 ELSE 4 END,created_at,id LIMIT ? OFFSET ?`).all(s,...params,s,q.pageSize,(q.page-1)*q.pageSize)as MediaCleanupJobRow[];
  const raw=this.database.prepare(`SELECT SUM(status='pending')pending,SUM(status='processing')processing,SUM(status='completed')completed,SUM(status='pending' AND attempts>=3)failing,SUM(status='processing' AND COALESCE(claimed_at,updated_at)<=datetime('now',?))stale FROM media_cleanup_jobs`).get(s)as Record<string,number|null>;return{rows,total,summary:Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Number(v)||0]))};}}
