import type{Pool,PoolClient}from"pg";import type{AdminUsersRepository}from"./repository.js";
import type{AuditContext,AuditEvent,CredentialsInput,LevelSource,ListInput,Row}from"./types.js";
export class PostgresAdminUsersRepository implements AdminUsersRepository{private readonly pool:Pool;constructor(pool:Pool){this.pool=pool;}
  async listUsers(input:ListInput){const values:number[]=[];const cursor=input.cursorId?`WHERE u.id<$${values.push(input.cursorId)}`:"",limit=input.limit?`LIMIT $${values.push(input.limit)}`:"";return(await this.pool.query(`SELECT u.id,u.username,u.email,u.phone,u.avatar_url,u.role,
    CASE WHEN u.is_verified_expert THEN 1 ELSE 0 END is_verified_expert,CASE WHEN COALESCE(u.is_disabled,FALSE) THEN 1 ELSE 0 END is_disabled,u.created_at,
    CASE WHEN hp.user_id IS NULL THEN 0 ELSE 1 END has_health_profile FROM users u LEFT JOIN user_health_profiles hp ON hp.user_id=u.id ${cursor} ORDER BY u.id DESC ${limit}`,values)).rows as Row[];}
  async levelSource(userId:number):Promise<LevelSource>{const c=(await this.pool.query(`SELECT(SELECT value FROM system_settings WHERE key='USER_LEVEL_RULE')"ruleJson",
    (SELECT COUNT(*) FROM diet_records WHERE user_id=$1)"dietRecordCount",(SELECT COUNT(*) FROM recipe_favorites WHERE user_id=$1)"favoriteCount",
    (SELECT COUNT(*) FROM community_posts WHERE user_id=$1 AND deleted_at IS NULL)"postCount",(SELECT COUNT(*) FROM user_follows WHERE following_id=$1)"followerCount",
    (SELECT COUNT(*) FROM user_daily_check_ins WHERE user_id=$1)"checkInCount",(SELECT COALESCE(SUM(xp_delta),0) FROM user_level_adjustments WHERE user_id=$1)"adjustmentXp"`,[userId])).rows[0] as Row;
    const dates=(await this.pool.query("SELECT DISTINCT recorded_at FROM diet_records WHERE user_id=$1",[userId])).rows as Array<{recorded_at:string}>;return{ruleJson:c.ruleJson?String(c.ruleJson):null,dietDates:dates.map(r=>r.recorded_at),dietRecordCount:Number(c.dietRecordCount),favoriteCount:Number(c.favoriteCount),postCount:Number(c.postCount),followerCount:Number(c.followerCount),checkInCount:Number(c.checkInCount),adjustmentXp:Number(c.adjustmentXp)};}
  async healthProfile(userId:number,context:AuditContext){return this.tx(async client=>{const target=(await client.query("SELECT id,username FROM users WHERE id=$1",[userId])).rows[0] as Row|undefined;if(!target)return null;
    const profile=((await client.query(`SELECT gender,age,height,weight,target_weight,health_goal,activity_level,dietary_preference,allergies_json,medications,medical_conditions_json,medical_notes,
      dietary_restrictions_json,disliked_foods,kitchen_constraints_json,nutrition_targets_json,tracking_enabled,updated_at FROM user_health_profiles WHERE user_id=$1`,[userId])).rows[0] as Row|undefined)||null;
    const latest=((await client.query(`SELECT id,recorded_date,weight,body_fat,water_ml,height_cm,waist_cm,hip_cm,resting_heart_rate,blood_pressure_systolic,blood_pressure_diastolic,
      blood_glucose_mmol,cycle_status,sleep_hours FROM health_logs WHERE user_id=$1 ORDER BY recorded_date DESC,id DESC LIMIT 1`,[userId])).rows[0] as Row|undefined)||null;
    const count=Number((await client.query("SELECT COUNT(*) count FROM health_logs WHERE user_id=$1",[userId])).rows[0].count);await this.audit(client,{...context,action:"user.health_profile.view",resourceType:"user",resourceId:userId,
      summary:`查看用户 ${target.username} 的健康与饮食档案`,details:{profileExists:Boolean(profile),trackingCount:count}});return{target,profile,latest,count};});}
  async adjustLevel(userId:number,xpDelta:number,reason:string,context:AuditContext){return this.tx(async client=>{const target=(await client.query("SELECT username FROM users WHERE id=$1 FOR UPDATE",[userId])).rows[0] as Row|undefined;if(!target)return false;
    await client.query("INSERT INTO user_level_adjustments(user_id,admin_user_id,xp_delta,reason)VALUES($1,$2,$3,$4)",[userId,context.adminUserId,xpDelta,reason]);await this.audit(client,{...context,action:"user.level.adjust",resourceType:"user",resourceId:userId,
      summary:`调整用户 ${target.username} 经验 ${xpDelta>0?"+":""}${xpDelta}`,details:{xpDelta,reason}});return true;});}
  async updateCredentials(userId:number,input:CredentialsInput,context:AuditContext){try{return await this.tx(async client=>{if(input.identifierUpdated)await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`admin-user-identifier:${input.email||input.phone}`]);
    const target=(await client.query("SELECT id,username,email,phone,role FROM users WHERE id=$1 FOR UPDATE",[userId])).rows[0] as Row|undefined;if(!target)return{kind:"not_found"as const};if(target.role==="admin")return{kind:"admin"as const};
    if(input.identifierUpdated&&(await client.query("SELECT 1 FROM users WHERE(email=$1 OR phone=$2)AND id<>$3",[input.email,input.phone,userId])).rowCount)return{kind:"duplicate"as const};
    const updates:string[]=[],values:unknown[]=[];const bind=(v:unknown)=>{values.push(v);return`$${values.length}`};if(input.identifierUpdated){updates.push(`email=${bind(input.email)}`,`phone=${bind(input.phone)}`);}if(input.passwordReset){updates.push(`password_hash=${bind(input.passwordHash)}`,"must_change_password=FALSE","session_version=session_version+1");}values.push(userId);
    await client.query(`UPDATE users SET ${updates.join(",")} WHERE id=$${values.length}`,values);await this.audit(client,{...context,action:"user.credentials.update",resourceType:"user",resourceId:userId,summary:`更新用户 ${target.username} 的登录信息`,details:{identifierUpdated:input.identifierUpdated,passwordReset:input.passwordReset}});
    return{kind:"updated"as const,user:(await client.query("SELECT id,username,email,phone FROM users WHERE id=$1",[userId])).rows[0] as Row};});}catch(e){if(pgUnique(e))return{kind:"duplicate"as const};throw e;}}
  async updateRole(userId:number,role:"admin"|"user",context:AuditContext){return this.change(userId,"role",role,context,"user.role.update",u=>`修改用户 ${u.username||userId} 的角色`,u=>({before:u.role,after:role}));}
  async updateExpert(userId:number,value:boolean,context:AuditContext){return this.change(userId,"is_verified_expert",value,context,"user.expert.update",u=>`${value?"认证":"取消认证"}专业用户 ${u.username}`,u=>({before:Boolean(u.is_verified_expert),after:value}));}
  async updateStatus(userId:number,value:boolean,context:AuditContext){return this.change(userId,"is_disabled",value,context,value?"user.disable":"user.enable",u=>`${value?"停用":"启用"}用户 ${u.username}`,u=>({before:Boolean(u.is_disabled),after:value}));}
  private change(userId:number,column:"role"|"is_verified_expert"|"is_disabled",value:unknown,context:AuditContext,action:string,summary:(u:Row)=>string,details:(u:Row)=>Row){return this.tx(async client=>{const u=(await client.query(`SELECT username,${column} FROM users WHERE id=$1 FOR UPDATE`,[userId])).rows[0]as Row|undefined;if(!u)return{kind:"not_found"as const};await client.query(`UPDATE users SET ${column}=$1 WHERE id=$2`,[value,userId]);await this.audit(client,{...context,action,resourceType:"user",resourceId:userId,summary:summary(u),details:details(u)});return{kind:"updated"as const};});}
  private audit(client:PoolClient,e:AuditEvent){return client.query(`INSERT INTO admin_audit_logs(admin_user_id,action,resource_type,resource_id,summary,details_json,ip_address,user_agent)VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8)`,[e.adminUserId,e.action,e.resourceType,String(e.resourceId),e.summary,e.details?JSON.stringify(e.details):null,e.ipAddress||null,e.userAgent||null]);}
  private async tx<T>(operation:(c:PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");const result=await operation(c);await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}}
function pgUnique(error:unknown){return typeof error==="object"&&error!==null&&"code"in error&&error.code==="23505";}
