import type Database from "better-sqlite3";import type {AdminUsersRepository} from "./repository.js";
import{levelRuleFrom,type UserLevelRule}from"../community/level.js";import type {AuditContext,AuditEvent,CredentialsInput,LevelSource,ListInput,Row} from "./types.js";
export class SqliteAdminUsersRepository implements AdminUsersRepository {private readonly database:Database.Database;constructor(database:Database.Database){this.database=database;}
  async listUsers(input:ListInput){const values:number[]=[];if(input.cursorId)values.push(input.cursorId);if(input.limit)values.push(input.limit);return this.database.prepare(`SELECT u.id,u.username,u.email,u.phone,u.avatar_url,u.role,u.is_verified_expert,
    COALESCE(u.is_disabled,0) AS is_disabled,u.created_at,CASE WHEN hp.user_id IS NULL THEN 0 ELSE 1 END AS has_health_profile FROM users u LEFT JOIN user_health_profiles hp ON hp.user_id=u.id
    ${input.cursorId?"WHERE u.id<?":""} ORDER BY u.id DESC ${input.limit?"LIMIT ?":""}`).all(...values) as Row[];}
  async levelSource(userId:number):Promise<LevelSource>{const c=this.database.prepare(`SELECT (SELECT value FROM system_settings WHERE key='USER_LEVEL_RULE') ruleJson,
    (SELECT COUNT(*) FROM diet_records WHERE user_id=?) dietRecordCount,(SELECT COUNT(*) FROM recipe_favorites WHERE user_id=?) favoriteCount,
    (SELECT COUNT(*) FROM community_posts WHERE user_id=? AND deleted_at IS NULL) postCount,(SELECT COUNT(*) FROM user_follows WHERE following_id=?) followerCount,
    (SELECT COUNT(*) FROM user_daily_check_ins WHERE user_id=?) checkInCount,(SELECT COALESCE(SUM(xp_delta),0) FROM user_level_adjustments WHERE user_id=?) adjustmentXp`).get(userId,userId,userId,userId,userId,userId) as Row;
    const dates=(this.database.prepare("SELECT DISTINCT recorded_at FROM diet_records WHERE user_id=?").all(userId) as Array<{recorded_at:string}>).map(r=>r.recorded_at);
    return{ruleJson:c.ruleJson?String(c.ruleJson):null,dietDates:dates,dietRecordCount:Number(c.dietRecordCount),favoriteCount:Number(c.favoriteCount),postCount:Number(c.postCount),followerCount:Number(c.followerCount),checkInCount:Number(c.checkInCount),adjustmentXp:Number(c.adjustmentXp)};}
  async healthProfile(userId:number,context:AuditContext){return this.database.transaction(()=>{const target=this.database.prepare("SELECT id,username FROM users WHERE id=?").get(userId) as Row|undefined;if(!target)return null;
    const profile=(this.database.prepare(`SELECT gender,age,height,weight,target_weight,health_goal,activity_level,dietary_preference,allergies_json,medications,medical_conditions_json,medical_notes,
      dietary_restrictions_json,disliked_foods,kitchen_constraints_json,nutrition_targets_json,tracking_enabled,updated_at FROM user_health_profiles WHERE user_id=?`).get(userId) as Row|undefined)||null;
    const latest=(this.database.prepare(`SELECT id,recorded_date,weight,body_fat,water_ml,height_cm,waist_cm,hip_cm,resting_heart_rate,blood_pressure_systolic,blood_pressure_diastolic,
      blood_glucose_mmol,cycle_status,sleep_hours FROM health_logs WHERE user_id=? ORDER BY recorded_date DESC,id DESC LIMIT 1`).get(userId) as Row|undefined)||null;
    const count=Number((this.database.prepare("SELECT COUNT(*) count FROM health_logs WHERE user_id=?").get(userId) as Row).count);this.audit({...context,action:"user.health_profile.view",resourceType:"user",resourceId:userId,
      summary:`查看用户 ${target.username} 的健康与饮食档案`,details:{profileExists:Boolean(profile),trackingCount:count}});return{target,profile,latest,count};})();}
  async adjustLevel(userId:number,xpDelta:number,reason:string,context:AuditContext){return this.database.transaction(()=>{const target=this.database.prepare("SELECT username FROM users WHERE id=?").get(userId) as Row|undefined;if(!target)return false;
    this.database.prepare("INSERT INTO user_level_adjustments (user_id,admin_user_id,xp_delta,reason) VALUES (?,?,?,?)").run(userId,context.adminUserId,xpDelta,reason);this.audit({...context,action:"user.level.adjust",resourceType:"user",resourceId:userId,
      summary:`调整用户 ${target.username} 经验 ${xpDelta>0?"+":""}${xpDelta}`,details:{xpDelta,reason}});return true;})();}
  async updateCredentials(userId:number,input:CredentialsInput,context:AuditContext){return this.database.transaction(()=>{const target=this.database.prepare("SELECT id,username,email,phone,role FROM users WHERE id=?").get(userId) as Row|undefined;
    if(!target)return{kind:"not_found" as const};if(target.role==="admin")return{kind:"admin" as const};if(input.identifierUpdated&&this.database.prepare("SELECT 1 FROM users WHERE (email=? OR phone=?) AND id<>?").get(input.email,input.phone,userId))return{kind:"duplicate" as const};
    const updates:string[]=[],values:unknown[]=[];if(input.identifierUpdated){updates.push("email=?","phone=?");values.push(input.email,input.phone);}if(input.passwordReset){updates.push("password_hash=?","must_change_password=0","session_version=session_version+1");values.push(input.passwordHash);}
    this.database.prepare(`UPDATE users SET ${updates.join(",")} WHERE id=?`).run(...values,userId);this.audit({...context,action:"user.credentials.update",resourceType:"user",resourceId:userId,summary:`更新用户 ${target.username} 的登录信息`,details:{identifierUpdated:input.identifierUpdated,passwordReset:input.passwordReset}});
    return{kind:"updated" as const,user:this.database.prepare("SELECT id,username,email,phone FROM users WHERE id=?").get(userId) as Row};})();}
  async updateRole(userId:number,role:"admin"|"user",context:AuditContext){return this.change(userId,"role",role,context,"user.role.update",(u)=>`修改用户 ${u.username||userId} 的角色`,(u)=>({before:u.role,after:role}));}
  async updateExpert(userId:number,value:boolean,context:AuditContext){return this.change(userId,"is_verified_expert",value?1:0,context,"user.expert.update",u=>`${value?"认证":"取消认证"}专业用户 ${u.username}`,u=>({before:Boolean(u.is_verified_expert),after:value}));}
  async updateStatus(userId:number,value:boolean,context:AuditContext){return this.change(userId,"is_disabled",value?1:0,context,value?"user.disable":"user.enable",u=>`${value?"停用":"启用"}用户 ${u.username}`,u=>({before:Boolean(u.is_disabled),after:value}));}
  async levelRule(){return((this.database.prepare("SELECT value FROM system_settings WHERE key='USER_LEVEL_RULE'").get()as{value:string}|undefined)?.value)||null;}
  async saveLevelRule(rule:UserLevelRule,context:AuditContext){this.database.transaction(()=>{const previous=this.database.prepare("SELECT value FROM system_settings WHERE key='USER_LEVEL_RULE'").get()as{value:string}|undefined;
    this.database.prepare(`INSERT INTO system_settings(key,value,updated_at)VALUES('USER_LEVEL_RULE',?,CURRENT_TIMESTAMP)ON CONFLICT(key)DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).run(JSON.stringify(rule));
    this.audit({...context,action:"user_level_rule.update",resourceType:"user_level_rule",resourceId:"global",summary:"更新账户成长等级规则",details:{previous:levelRuleFrom(previous?.value||null),current:rule}});})();}
  private change(userId:number,column:"role"|"is_verified_expert"|"is_disabled",value:unknown,context:AuditContext,action:string,summary:(u:Row)=>string,details:(u:Row)=>Row){return Promise.resolve(this.database.transaction(()=>{const u=this.database.prepare(`SELECT username,${column} FROM users WHERE id=?`).get(userId) as Row|undefined;if(!u)return{kind:"not_found" as const};this.database.prepare(`UPDATE users SET ${column}=? WHERE id=?`).run(value,userId);
    this.audit({...context,action,resourceType:"user",resourceId:userId,summary:summary(u),details:details(u)});return{kind:"updated" as const};})());}
  private audit(e:AuditEvent){this.database.prepare(`INSERT INTO admin_audit_logs (admin_user_id,action,resource_type,resource_id,summary,details_json,ip_address,user_agent) VALUES (?,?,?,?,?,?,?,?)`)
    .run(e.adminUserId,e.action,e.resourceType,String(e.resourceId),e.summary,e.details?JSON.stringify(e.details):null,e.ipAddress||null,e.userAgent||null);}}
