import type { LevelSource } from "../community/types.js";
export type Row=Record<string,any>;
export type AuditContext={adminUserId:number;ipAddress?:string|null;userAgent?:string|null};
export type AuditEvent=AuditContext&{action:string;resourceType:string;resourceId:number|string;summary:string;details?:Row};
export type ListInput={cursorId:number|null;limit:number|null};
export type HealthProfileResult={target:Row;profile:Row|null;latest:Row|null;count:number}|null;
export type CredentialsInput={email:string|null;phone:string|null;identifierUpdated:boolean;passwordHash:string|null;passwordReset:boolean};
export type CredentialsResult={kind:"updated";user:Row}|{kind:"not_found"}|{kind:"admin"}|{kind:"duplicate"};
export type UpdateResult={kind:"updated"}|{kind:"not_found"};
export type {LevelSource};
