CREATE TABLE "feedback_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"feedback_id" integer NOT NULL,
	"author_id" integer,
	"author_role" text NOT NULL,
	"visibility" text NOT NULL,
	"content" text NOT NULL,
	"status" text NOT NULL,
	"request_key" text NOT NULL,
	"fingerprint" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "feedback_messages_check_1" CHECK (author_role IN ('user','admin')),
	CONSTRAINT "feedback_messages_check_2" CHECK (visibility IN ('public','internal'))
);
--> statement-breakpoint
ALTER TABLE "user_feedback" ADD COLUMN "request_key" text;--> statement-breakpoint
ALTER TABLE "user_feedback" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "user_feedback" ADD COLUMN "updated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "user_notification_inbox" ADD COLUMN "feedback_id" integer;--> statement-breakpoint
ALTER TABLE "feedback_messages" ADD CONSTRAINT "feedback_messages_feedback_id_user_feedback_id_fk" FOREIGN KEY ("feedback_id") REFERENCES "public"."user_feedback"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedback_messages" ADD CONSTRAINT "feedback_messages_author_id_users_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_feedback_message_thread" ON "feedback_messages" USING btree ("feedback_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_feedback_message_request" ON "feedback_messages" USING btree ("feedback_id","author_id","request_key");--> statement-breakpoint
ALTER TABLE "user_notification_inbox" ADD CONSTRAINT "user_notification_inbox_feedback_id_user_feedback_id_fk" FOREIGN KEY ("feedback_id") REFERENCES "public"."user_feedback"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_feedback_status" ON "user_feedback" USING btree ("status","id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_feedback_request" ON "user_feedback" USING btree ("user_id","request_key");
--> statement-breakpoint
UPDATE user_feedback SET status='received' WHERE status='open';
--> statement-breakpoint
UPDATE user_feedback SET updated_at=created_at WHERE updated_at IS NULL;
