import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

type Concept = {
  concept_id: string;
  preferred_name_zh: string;
  concept_level: "root" | "category" | "type";
  parent_concept_id: string;
  parent_concept_name: string;
  concept_category: string;
  is_electric: boolean;
  definition_scope: string;
  boundary_note: string;
  status: string;
  source_release: string;
};

type Alias = {
  concept_id: string;
  alias: string;
  normalized_alias: string;
  alias_type: string;
  language: string;
  source: string;
};

const RELEASE = "kitchenware-concept-layer-v4-20260901";
const SOURCE_ZIP_SHA256 = "787e5984db145f111ef04d346bca27ff5b61faf41718028bc74697c69e1a600a";
const EXPECTED_CONCEPT_SHA256 = "a8526d290364d70cee89d767d6f37b95da1778c266655e55036b26912f657d40";
const EXPECTED_ALIAS_SHA256 = "a0cea097723b0e2a93dfdc86221083d73f8039455d0238c21f8736eb230c9ff4";
const EXPECTED_TYPE_COUNT = 241;
const EXPECTED_ALIAS_COUNT = 521;

const legacySeedNames = new Set([
  "空气炸锅", "电饭煲", "微波炉", "烤箱", "破壁机", "豆浆机", "平底锅", "炒锅", "汤锅", "蒸锅", "砂锅", "压力锅",
  "多功能锅", "慢炖锅", "蒸烤一体机", "电磁炉", "洗碗机", "榨汁机", "手持搅拌器", "真空封口机", "奶锅", "焖烧锅",
  "厨师刀", "菜刀", "砧板", "电子秤", "厨房温度计", "厨房计时器", "压蒜器", "磨刀器", "隔热手套", "量杯量勺",
  "烤盘", "蛋糕模具", "打蛋器", "硅胶刮刀", "饭碗", "汤碗", "餐盘", "马克杯", "玻璃保鲜盒", "筷子", "汤匙", "锅铲",
  "漏勺", "厨房夹", "削皮器", "开罐器", "滤网", "沥水篮", "擀面杖", "厨房剪刀", "调味罐", "密封罐",
]);

function sha256(filePath: string) {
  return createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

function readJsonl<T>(filePath: string): T[] {
  return fs.readFileSync(filePath, "utf8").split(/\r?\n/).filter(Boolean).map((line) => JSON.parse(line) as T);
}

function appCategory(concept: Concept) {
  if (concept.concept_category === "锅具与烘焙器具") {
    return /烘焙|烤盘|模具|揉面|隔热手套|烘焙纸|吸油纸/.test(concept.preferred_name_zh) ? "烘焙工具" : "烹饪锅具";
  }
  if (concept.concept_category === "餐具与食物容器" || concept.concept_category === "刀具与手动工具") return "刀具餐具";
  if (["烹饪电器", "料理与饮品电器", "制冷与清洗电器", "厨卫电器"].includes(concept.concept_category)) return "小家电";
  return "其他";
}

const inputArgument = process.argv.slice(2).find((argument) => argument !== "--");
const inputDirectory = inputArgument ? path.resolve(inputArgument) : "";
if (!inputDirectory) throw new Error("Usage: pnpm --dir server data:kitchenware:generate -- /absolute/path/to/extracted-v4");

const conceptPath = path.join(inputDirectory, "canonical-concepts-v4.jsonl");
const aliasPath = path.join(inputDirectory, "concept-aliases-v4.jsonl");
if (sha256(conceptPath) !== EXPECTED_CONCEPT_SHA256) throw new Error("canonical-concepts-v4.jsonl checksum mismatch");
if (sha256(aliasPath) !== EXPECTED_ALIAS_SHA256) throw new Error("concept-aliases-v4.jsonl checksum mismatch");

const concepts = readJsonl<Concept>(conceptPath).filter((concept) => concept.concept_level === "type");
const aliases = readJsonl<Alias>(aliasPath);
if (concepts.length !== EXPECTED_TYPE_COUNT) throw new Error(`Expected ${EXPECTED_TYPE_COUNT} type concepts, found ${concepts.length}`);
if (aliases.length !== EXPECTED_ALIAS_COUNT) throw new Error(`Expected ${EXPECTED_ALIAS_COUNT} aliases, found ${aliases.length}`);

const aliasesByConcept = new Map<string, Alias[]>();
for (const alias of aliases) {
  const values = aliasesByConcept.get(alias.concept_id) || [];
  values.push(alias);
  aliasesByConcept.set(alias.concept_id, values);
}

const rows = concepts.map((concept) => ({
  conceptId: concept.concept_id,
  name: concept.preferred_name_zh,
  category: appCategory(concept),
  sourceCategory: concept.concept_category,
  parentConceptId: concept.parent_concept_id,
  parentConceptName: concept.parent_concept_name,
  isElectric: concept.is_electric,
  aliases: (aliasesByConcept.get(concept.concept_id) || [])
    .filter((alias) => alias.normalized_alias !== concept.preferred_name_zh)
    .map((alias) => alias.alias),
  definitionScope: concept.definition_scope,
  boundaryNote: concept.boundary_note,
  status: concept.status,
  replacesLegacySeed: legacySeedNames.has(concept.preferred_name_zh),
})).sort((left, right) => left.name.localeCompare(right.name, "zh-CN"));

const output = `// Generated by server/scripts/generate-kitchenware-catalog-v4.ts. Do not edit by hand.\n`
  + `export const KITCHENWARE_CATALOG_V4_RELEASE = ${JSON.stringify({
    release: RELEASE,
    sourceZipSha256: SOURCE_ZIP_SHA256,
    conceptFileSha256: EXPECTED_CONCEPT_SHA256,
    aliasFileSha256: EXPECTED_ALIAS_SHA256,
    typeConcepts: EXPECTED_TYPE_COUNT,
    aliases: EXPECTED_ALIAS_COUNT,
  }, null, 2)} as const;\n\n`
  + `export const KITCHENWARE_CATALOG_V4 = ${JSON.stringify(rows, null, 2)} as const;\n`;

const outputPath = path.resolve("src/data/kitchenwareCatalogV4.generated.ts");
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
console.log(`Generated ${path.relative(process.cwd(), outputPath)} with ${rows.length} concepts.`);
