import React from "react";
import renderer, { act } from "react-test-renderer";
import { TextInput, TouchableOpacity, Text } from "react-native";
const mockRequest = jest.fn();
const mockLogout = jest.fn(async () => undefined);
const mockReplace = jest.fn();
jest.mock("@/components/Screen", () => ({ Screen: ({ children }: { children: React.ReactNode }) => children }));
jest.mock("@/contexts/AuthContext", () => ({ useAuth: () => ({ user: { id: 1 }, logout: mockLogout, sessionGeneration: 4 }), useAuthFetch: () => jest.fn() }));
jest.mock("@/hooks/useSafeRouter", () => ({ useSafeRouter: () => ({ replace: mockReplace, back: jest.fn() }), useSafeSearchParams: () => ({}) }));
jest.mock("@/services/api/client", () => ({ requestJson: (...args: unknown[]) => mockRequest(...args) }));
import PasswordScreen from "./index";
test("mismatch never sends credentials; successful change revokes the captured session", async () => {
  let tree!: renderer.ReactTestRenderer;
  await act(async () => { tree = renderer.create(<PasswordScreen />); });
  const inputs = tree.root.findAllByType(TextInput);
  act(() => { inputs[0].props.onChangeText("OldPassword1"); inputs[1].props.onChangeText("NewPassword2"); inputs[2].props.onChangeText("different"); });
  const submit = () => tree.root.findAllByType(TouchableOpacity).find(item => item.findAllByType(Text).some(text => text.props.children === "修改密码并重新登录"))!.props.onPress();
  await act(async () => { submit(); });
  expect(mockRequest).not.toHaveBeenCalled();
  expect(JSON.stringify(tree.toJSON())).toContain("两次输入的新密码不一致");
  act(() => inputs[2].props.onChangeText("NewPassword2"));
  mockRequest.mockRejectedValueOnce(new Error("当前密码不正确"));
  await act(async () => { submit(); });
  expect(mockLogout).not.toHaveBeenCalled();
  expect(JSON.stringify(tree.toJSON())).toContain("当前密码不正确");
  mockRequest.mockResolvedValueOnce({ success: true });
  await act(async () => { submit(); });
  expect(mockLogout).toHaveBeenCalledWith("密码已修改，请使用新密码重新登录。", 4);
  expect(mockReplace).toHaveBeenCalledWith("/login");
  act(() => tree.unmount());
});
