// Generated by scripts/generate-postgres-baseline.mjs. Do not edit by hand.
// SQLite final-schema SHA-256: 82f21836cc87a803b68d16e514fc7848699832e4ecc23961250ea42d0b7c7027
import { sql } from "drizzle-orm";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { bigint, boolean, check, customType, doublePrecision, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique, uniqueIndex } from "drizzle-orm/pg-core";
const bytea = customType<{ data: Buffer; driverData: Buffer }>({ dataType: () => "bytea" });

export const adminAuditLogs = pgTable("admin_audit_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  admin_user_id: integer("admin_user_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  action: text("action").notNull(),
  resource_type: text("resource_type").notNull(),
  resource_id: text("resource_id"),
  summary: text("summary").notNull(),
  details_json: jsonb("details_json"),
  ip_address: text("ip_address"),
  user_agent: text("user_agent"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  index("idx_admin_audit_logs_admin_created_at").on(table.admin_user_id, table.created_at),
  index("idx_admin_audit_logs_created_at").on(table.created_at),
]);

export const agentActions = pgTable("agent_actions", {
  id: text("id").primaryKey().notNull(),
  run_id: text("run_id").notNull().references((): AnyPgColumn => agentRuns.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  action_type: text("action_type").notNull(),
  risk_level: text("risk_level").notNull(),
  status: text("status").notNull(),
  payload_json: jsonb("payload_json").notNull(),
  before_json: jsonb("before_json"),
  result_json: jsonb("result_json"),
  idempotency_key: text("idempotency_key").notNull(),
  version: integer("version").notNull().default(1),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }),
  executed_at: timestamp("executed_at", { withTimezone: true, mode: "string" }),
  undone_at: timestamp("undone_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  approval_decision: text("approval_decision"),
  approved_by_user_id: integer("approved_by_user_id"),
  approved_at: timestamp("approved_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  index("idx_agent_actions_run_status").on(table.run_id, table.status),
  unique("agent_actions_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
  check("agent_actions_check_1", sql.raw("risk_level IN ('low', 'high', 'forbidden')")),
  check("agent_actions_check_2", sql.raw("status IN ('proposed', 'awaiting_approval', 'executed', 'rejected', 'undone', 'failed', 'expired')")),
]);

export const agentRunEvents = pgTable("agent_run_events", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  run_id: text("run_id").notNull().references((): AnyPgColumn => agentRuns.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  agent_name: text("agent_name").notNull(),
  event_type: text("event_type").notNull(),
  summary: text("summary").notNull(),
  payload_json: jsonb("payload_json"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_agent_run_events_run_sequence").on(table.run_id, table.sequence),
  unique("agent_run_events_run_id_sequence_key").on(table.run_id, table.sequence),
]);

export const agentRunMedia = pgTable("agent_run_media", {
  id: text("id").primaryKey().notNull(),
  run_id: text("run_id").notNull().references((): AnyPgColumn => agentRuns.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  kind: text("kind").notNull(),
  mime_type: text("mime_type"),
  data_base64: text("data_base64").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_agent_run_media_run").on(table.run_id),
  check("agent_run_media_check_1", sql.raw("kind IN ('image', 'audio')")),
]);

export const agentRuns = pgTable("agent_runs", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  session_id: text("session_id").notNull(),
  modality: text("modality").notNull(),
  source: text("source").notNull().default("assistant"),
  status: text("status").notNull().default("queued"),
  input_json: jsonb("input_json").notNull(),
  result_json: jsonb("result_json"),
  pending_approval_json: jsonb("pending_approval_json"),
  error_code: text("error_code"),
  error_message: text("error_message"),
  checkpoint_thread_id: text("checkpoint_thread_id").notNull(),
  started_at: timestamp("started_at", { withTimezone: true, mode: "string" }),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  pending_input_json: jsonb("pending_input_json"),
}, (table) => [
  index("idx_agent_runs_session").on(table.user_id, table.session_id, table.created_at.desc()),
  index("idx_agent_runs_status_updated").on(table.status, table.updated_at),
  index("idx_agent_runs_user_created").on(table.user_id, table.created_at.desc()),
  check("agent_runs_check_1", sql.raw("modality IN ('text', 'home', 'cooking', 'image', 'audio', 'inventory_scan', 'receipt')")),
  check("agent_runs_check_2", sql.raw("status IN ('queued', 'running', 'awaiting_input', 'awaiting_approval', 'completed', 'failed', 'cancelled', 'expired')")),
]);

export const aiChatMessages = pgTable("ai_chat_messages", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  session_id: text("session_id").notNull(),
  role: text("role").notNull(),
  content: text("content").notNull(),
  response_time_ms: integer("response_time_ms"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  source: text("source").notNull().default("legacy"),
  status: text("status").notNull().default("completed"),
  payload_json: jsonb("payload_json"),
  confirmation_id: text("confirmation_id"),
}, (table) => [
  index("idx_ai_chat_messages_confirmation").on(table.confirmation_id).where(sql.raw("confirmation_id IS NOT NULL")),
  index("idx_ai_chat_messages_source_created").on(table.source, table.created_at.desc()),
  index("idx_ai_chat_messages_created_at").on(table.created_at.desc()),
  index("idx_ai_chat_messages_session").on(table.user_id, table.session_id, table.created_at),
  check("ai_chat_messages_check_1", sql.raw("role IN ('system', 'user', 'assistant')")),
]);

export const aiChatSessionDeletions = pgTable("ai_chat_session_deletions", {
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  session_id: text("session_id").notNull(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ name: "ai_chat_session_deletions_pkey", columns: [table.user_id, table.session_id] }),
  index("idx_ai_chat_session_deletions_time").on(table.deleted_at),
]);

export const aiUsageLogs = pgTable("ai_usage_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  endpoint: text("endpoint").notNull(),
  model: text("model").notNull(),
  prompt_tokens: integer("prompt_tokens").default(0),
  completion_tokens: integer("completion_tokens").default(0),
  total_tokens: integer("total_tokens").default(0),
  latency_ms: integer("latency_ms").default(0),
  success: boolean("success").default(true),
  estimated_cost_usd: doublePrecision("estimated_cost_usd").default(0),
  failure_reason: text("failure_reason"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  run_id: text("run_id"),
  agent_name: text("agent_name"),
  phase: text("phase"),
}, (table) => [
  index("idx_ai_usage_logs_run_agent").on(table.run_id, table.agent_name, table.created_at),
  index("idx_ai_usage_logs_user_created_at").on(table.user_id, table.created_at),
  index("idx_ai_usage_logs_created_at").on(table.created_at),
]);

export const aiWriteAuditLogs = pgTable("ai_write_audit_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  confirmation_id: text("confirmation_id").notNull().references((): AnyPgColumn => aiWriteConfirmations.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  action: text("action").notNull(),
  event: text("event").notNull(),
  details_json: jsonb("details_json"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
]);

export const aiWriteConfirmations = pgTable("ai_write_confirmations", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  conversation_id: text("conversation_id"),
  source_message_id: text("source_message_id"),
  action: text("action").notNull(),
  payload_json: jsonb("payload_json").notNull(),
  status: text("status").notNull().default("preview"),
  idempotency_key: text("idempotency_key"),
  committed_result_json: jsonb("committed_result_json"),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }).notNull(),
  committed_at: timestamp("committed_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_ai_write_confirmations_user_status").on(table.user_id, table.status, table.expires_at),
  uniqueIndex("idx_ai_write_confirmations_user_idempotency").on(table.user_id, table.idempotency_key).where(sql.raw("idempotency_key IS NOT NULL")),
  check("ai_write_confirmations_check_1", sql.raw("status IN ('preview', 'committed', 'expired', 'cancelled')")),
]);

export const authVerificationChallenges = pgTable("auth_verification_challenges", {
  id: text("id").primaryKey().notNull(),
  subject_id: integer("subject_id").notNull().references((): AnyPgColumn => authVerificationSubjects.id, { onDelete: "cascade" }),
  purpose: text("purpose").notNull().default("login"),
  out_id: text("out_id").notNull(),
  biz_id: text("biz_id"),
  provider_request_id: text("provider_request_id"),
  status: text("status").notNull().default("pending"),
  attempt_count: integer("attempt_count").notNull().default(0),
  registration_token_hash: text("registration_token_hash"),
  registration_expires_at: timestamp("registration_expires_at", { withTimezone: true, mode: "string" }),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }).notNull(),
  verified_at: timestamp("verified_at", { withTimezone: true, mode: "string" }),
  consumed_at: timestamp("consumed_at", { withTimezone: true, mode: "string" }),
  source_ip: text("source_ip"),
  user_agent: text("user_agent"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  uniqueIndex("idx_auth_challenges_registration_token").on(table.registration_token_hash).where(sql.raw("registration_token_hash IS NOT NULL")),
  index("idx_auth_challenges_biz_out").on(table.biz_id, table.out_id),
  index("idx_auth_challenges_subject_created").on(table.subject_id, table.created_at.desc()),
  unique("auth_verification_challenges_out_id_key").on(table.out_id),
]);

export const authVerificationEvents = pgTable("auth_verification_events", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  subject_id: integer("subject_id").notNull().references((): AnyPgColumn => authVerificationSubjects.id, { onDelete: "cascade" }),
  challenge_id: text("challenge_id").references((): AnyPgColumn => authVerificationChallenges.id, { onDelete: "cascade" }),
  channel: text("channel").notNull(),
  provider: text("provider").notNull(),
  event_type: text("event_type").notNull(),
  outcome: text("outcome").notNull(),
  provider_code: text("provider_code"),
  provider_message: text("provider_message"),
  provider_request_id: text("provider_request_id"),
  biz_id: text("biz_id"),
  out_id: text("out_id"),
  source_ip: text("source_ip"),
  user_agent: text("user_agent"),
  details_json: jsonb("details_json"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_auth_events_provider_ids").on(table.biz_id, table.out_id, table.provider_request_id),
  index("idx_auth_events_ip_created").on(table.source_ip, table.created_at.desc()),
  index("idx_auth_events_subject_created").on(table.subject_id, table.created_at.desc()),
]);

export const authVerificationSubjects = pgTable("auth_verification_subjects", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  channel: text("channel").notNull(),
  provider: text("provider").notNull(),
  subject_hmac: text("subject_hmac").notNull(),
  subject_ciphertext: text("subject_ciphertext").notNull(),
  subject_iv: text("subject_iv").notNull(),
  subject_auth_tag: text("subject_auth_tag").notNull(),
  last_seen_at: timestamp("last_seen_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_auth_subjects_user").on(table.user_id, table.channel),
  unique("auth_verification_subjects_channel_provider_subject_hmac_key").on(table.channel, table.provider, table.subject_hmac),
  check("auth_verification_subjects_check_1", sql.raw("channel IN ('sms', 'captcha', 'phone')")),
]);

export const authVerificationUsageDaily = pgTable("auth_verification_usage_daily", {
  usage_date: text("usage_date").notNull(),
  channel: text("channel").notNull(),
  provider: text("provider").notNull(),
  send_requests: integer("send_requests").notNull().default(0),
  send_api_calls: integer("send_api_calls").notNull().default(0),
  accepted: integer("accepted").notNull().default(0),
  delivered: integer("delivered").notNull().default(0),
  delivery_failed: integer("delivery_failed").notNull().default(0),
  verify_api_calls: integer("verify_api_calls").notNull().default(0),
  verify_passed: integer("verify_passed").notNull().default(0),
  verify_failed: integer("verify_failed").notNull().default(0),
  local_rate_limited: integer("local_rate_limited").notNull().default(0),
  provider_errors: integer("provider_errors").notNull().default(0),
  delivery_units: integer("delivery_units").notNull().default(0),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ name: "auth_verification_usage_daily_pkey", columns: [table.usage_date, table.channel, table.provider] }),
]);

export const communityCommentLikes = pgTable("community_comment_likes", {
  comment_id: integer("comment_id").notNull().references((): AnyPgColumn => communityComments.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  primaryKey({ name: "community_comment_likes_pkey", columns: [table.comment_id, table.user_id] }),
]);

export const communityComments = pgTable("community_comments", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  post_id: integer("post_id").notNull().references((): AnyPgColumn => communityPosts.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  username: text("username").notNull(),
  nickname: text("nickname"),
  avatar_url: text("avatar_url"),
  content: text("content").notNull(),
  image_url: text("image_url"),
  likes_count: integer("likes_count").default(0),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  index("idx_community_comments_post_created").on(table.post_id, table.created_at.desc()),
]);

export const communityEventParticipants = pgTable("community_event_participants", {
  post_id: integer("post_id").notNull().references((): AnyPgColumn => communityPosts.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  primaryKey({ name: "community_event_participants_pkey", columns: [table.post_id, table.user_id] }),
  index("idx_community_event_participants_post").on(table.post_id, table.created_at.desc()),
]);

export const communityPostLikes = pgTable("community_post_likes", {
  post_id: integer("post_id").notNull().references((): AnyPgColumn => communityPosts.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  primaryKey({ name: "community_post_likes_pkey", columns: [table.post_id, table.user_id] }),
]);

export const communityPosts = pgTable("community_posts", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  username: text("username").notNull(),
  nickname: text("nickname"),
  avatar_url: text("avatar_url"),
  category: text("category").default("寻味"),
  content: text("content").notNull(),
  image_url: text("image_url"),
  image_urls: text("image_urls"),
  event_start_at: timestamp("event_start_at", { withTimezone: true, mode: "string" }),
  event_end_at: timestamp("event_end_at", { withTimezone: true, mode: "string" }),
  question_status: text("question_status").default("open"),
  accepted_comment_id: integer("accepted_comment_id"),
  likes_count: integer("likes_count").default(0),
  views_count: integer("views_count").default(0),
  comment_count: integer("comment_count").default(0),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  deleted_by: integer("deleted_by"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  ip_location: text("ip_location"),
  linked_recipe_id: integer("linked_recipe_id").references((): AnyPgColumn => recipes.id, { onDelete: "set null" }),
}, (table) => [
  index("idx_community_posts_deleted_at").on(table.deleted_at),
  index("idx_community_posts_linked_recipe").on(table.linked_recipe_id).where(sql.raw("linked_recipe_id IS NOT NULL")),
  index("idx_community_posts_feed_page").on(table.deleted_at, table.created_at.desc(), table.id.desc()),
]);

export const communityShareCodes = pgTable("community_share_codes", {
  code: text("code").primaryKey().notNull(),
  post_id: integer("post_id").notNull().references((): AnyPgColumn => communityPosts.id, { onDelete: "cascade" }),
  created_by: integer("created_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_community_share_codes_post").on(table.post_id, table.expires_at.desc()),
]);

export const cookingCompletions = pgTable("cooking_completions", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  recipe_id: integer("recipe_id"),
  diet_record_id: integer("diet_record_id").notNull().references((): AnyPgColumn => dietRecords.id, { onDelete: "cascade" }),
  consumed_inventory_ids_json: jsonb("consumed_inventory_ids_json").notNull().default(sql.raw("'[]'::jsonb")),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_cooking_completions_user_created").on(table.user_id, table.created_at.desc()),
  unique("cooking_completions_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
]);

export const cookingQueueItems = pgTable("cooking_queue_items", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  position: integer("position").notNull(),
  status: text("status").notNull().default("waiting"),
  meal_type: text("meal_type"),
  planned_at: timestamp("planned_at", { withTimezone: true, mode: "string" }),
  recipe_snapshot_json: jsonb("recipe_snapshot_json").notNull().default(sql.raw("'{}'::jsonb")),
  prepared_ingredients_json: jsonb("prepared_ingredients_json").notNull().default(sql.raw("'[]'::jsonb")),
  shopping_list_synced_at: timestamp("shopping_list_synced_at", { withTimezone: true, mode: "string" }),
  idempotency_key: text("idempotency_key"),
  version: integer("version").notNull().default(1),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_cooking_queue_user_history").on(table.user_id, table.updated_at.desc()),
  index("idx_cooking_queue_user_position").on(table.user_id, table.position, table.created_at).where(sql.raw("deleted_at IS NULL AND status IN ('waiting', 'preparing', 'ready', 'cooking')")),
  uniqueIndex("idx_cooking_queue_idempotency").on(table.user_id, table.idempotency_key).where(sql.raw("idempotency_key IS NOT NULL")),
  uniqueIndex("idx_cooking_queue_active_recipe").on(table.user_id, table.recipe_id).where(sql.raw("deleted_at IS NULL AND status IN ('waiting', 'preparing', 'ready', 'cooking')")),
  check("cooking_queue_items_check_1", sql.raw("status IN ('waiting', 'preparing', 'ready', 'cooking', 'completed', 'cancelled')")),
  check("cooking_queue_items_check_2", sql.raw("meal_type IS NULL OR meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')")),
]);

export const dietRecords = pgTable("diet_records", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  meal_type: text("meal_type").notNull(),
  food_name: text("food_name").notNull(),
  amount: text("amount").notNull(),
  calories: integer("calories"),
  protein: doublePrecision("protein").default(0),
  carbs: doublePrecision("carbs").default(0),
  fat: doublePrecision("fat").default(0),
  image_url: text("image_url"),
  recorded_at: text("recorded_at").notNull(),
  recorded_time: text("recorded_time"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  index("idx_diet_records_user_date_time").on(table.user_id, table.recorded_at, table.recorded_time.desc(), table.id.desc()),
]);

export const funnelEvents = pgTable("funnel_events", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  event_name: text("event_name").notNull(),
  actor_hash: text("actor_hash").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_funnel_events_name_created").on(table.event_name, table.created_at.desc()),
]);

export const healthLogs = pgTable("health_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  weight: doublePrecision("weight"),
  body_fat: doublePrecision("body_fat"),
  water_ml: integer("water_ml").default(0),
  height_cm: doublePrecision("height_cm"),
  waist_cm: doublePrecision("waist_cm"),
  hip_cm: doublePrecision("hip_cm"),
  resting_heart_rate: integer("resting_heart_rate"),
  blood_pressure_systolic: integer("blood_pressure_systolic"),
  blood_pressure_diastolic: integer("blood_pressure_diastolic"),
  blood_glucose_mmol: doublePrecision("blood_glucose_mmol"),
  cycle_status: text("cycle_status"),
  sleep_hours: doublePrecision("sleep_hours"),
  recorded_date: text("recorded_date").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
]);

export const householdActivityLogs = pgTable("household_activity_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  household_id: integer("household_id").notNull().references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  operator_user_id: integer("operator_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  action: text("action").notNull(),
  food_name: text("food_name").notNull(),
  quantity: text("quantity").notNull(),
  storage_location: text("storage_location").default("冷藏"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
]);

export const householdInventoryItems = pgTable("household_inventory_items", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  household_id: integer("household_id").notNull().references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  created_by_user_id: integer("created_by_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  food_name: text("food_name").notNull(),
  category: text("category").notNull(),
  quantity: text("quantity").notNull(),
  expiration_date: text("expiration_date").notNull(),
  storage_location: text("storage_location").default("冷藏"),
  image_url: text("image_url"),
  is_available: boolean("is_available").default(true),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  version: integer("version").notNull().default(1),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
]);

export const householdMembers = pgTable("household_members", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  household_id: integer("household_id").notNull().references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  role: text("role").default("member"),
  joined_at: timestamp("joined_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  unique("household_members_household_id_user_id_key").on(table.household_id, table.user_id),
]);

export const householdShoppingIntakeBatches = pgTable("household_shopping_intake_batches", {
  id: text("id").primaryKey().notNull(),
  household_id: integer("household_id").notNull().references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("household_shopping_intake_batches_household_id_idempotency_key_key").on(table.household_id, table.idempotency_key),
]);

export const householdShoppingItems = pgTable("household_shopping_items", {
  id: text("id").primaryKey().notNull(),
  household_id: integer("household_id").notNull().references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  amount: text("amount").notNull().default("适量"),
  category: text("category").notNull().default("其他"),
  checked: boolean("checked").notNull().default(false),
  storage_location: text("storage_location"),
  expiration_date: text("expiration_date"),
  created_by_user_id: integer("created_by_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  updated_by_user_id: integer("updated_by_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  purchased_by_user_id: integer("purchased_by_user_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  version: integer("version").notNull().default(1),
  transferred_at: timestamp("transferred_at", { withTimezone: true, mode: "string" }),
  intake_batch_id: text("intake_batch_id"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  index("idx_household_shopping_name").on(table.household_id, table.name).where(sql.raw("deleted_at IS NULL AND transferred_at IS NULL")),
  index("idx_household_shopping_active").on(table.household_id, table.checked, table.updated_at.desc()).where(sql.raw("deleted_at IS NULL AND transferred_at IS NULL")),
]);

export const households = pgTable("households", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  name: text("name").notNull(),
  invite_code: text("invite_code").notNull(),
  owner_id: integer("owner_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  version: integer("version").notNull().default(1),
}, (table) => [
  unique("households_invite_code_key").on(table.invite_code),
]);

export const ingredientAliases = pgTable("ingredient_aliases", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  ingredient_id: integer("ingredient_id").notNull().references((): AnyPgColumn => ingredientsLibrary.id, { onDelete: "cascade" }),
  alias: text("alias").notNull(),
  normalized_alias: text("normalized_alias").notNull(),
  locale: text("locale").notNull().default("zh-CN"),
  alias_type: text("alias_type").notNull().default("synonym"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_ingredient_aliases_lookup").on(table.normalized_alias, table.ingredient_id),
  unique("ingredient_aliases_ingredient_id_normalized_alias_key").on(table.ingredient_id, table.normalized_alias),
]);

export const ingredientImportBatchItems = pgTable("ingredient_import_batch_items", {
  batch_id: text("batch_id").notNull().references((): AnyPgColumn => ingredientImportBatches.id, { onDelete: "cascade" }),
  ingredient_id: integer("ingredient_id").notNull().references((): AnyPgColumn => ingredientsLibrary.id, { onDelete: "cascade" }),
  action: text("action").notNull(),
  before_json: jsonb("before_json"),
  after_json: jsonb("after_json").notNull(),
}, (table) => [
  primaryKey({ name: "ingredient_import_batch_items_pkey", columns: [table.batch_id, table.ingredient_id] }),
  check("ingredient_import_batch_items_check_1", sql.raw("action IN ('insert', 'update')")),
]);

export const ingredientImportBatches = pgTable("ingredient_import_batches", {
  id: text("id").primaryKey().notNull(),
  source: text("source").notNull(),
  source_version: text("source_version").notNull(),
  data_license: text("data_license").notNull(),
  status: text("status").notNull(),
  stats_json: jsonb("stats_json").notNull().default(sql.raw("'{}'::jsonb")),
  error_json: jsonb("error_json"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  rolled_back_at: timestamp("rolled_back_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  check("ingredient_import_batches_check_1", sql.raw("status IN ('running', 'validated', 'committed', 'rolled_back', 'failed')")),
]);

export const ingredientPortions = pgTable("ingredient_portions", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  ingredient_id: integer("ingredient_id").notNull().references((): AnyPgColumn => ingredientsLibrary.id, { onDelete: "cascade" }),
  label: text("label").notNull(),
  grams: doublePrecision("grams").notNull(),
  source: text("source").notNull(),
  source_version: text("source_version"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("ingredient_portions_ingredient_id_label_key").on(table.ingredient_id, table.label),
  check("ingredient_portions_check_1", sql.raw("grams > 0")),
]);

export const ingredientSearchGaps = pgTable("ingredient_search_gaps", {
  normalized_query: text("normalized_query").primaryKey().notNull(),
  sample_query: text("sample_query").notNull(),
  hit_count: integer("hit_count").notNull().default(1),
  first_seen_at: timestamp("first_seen_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  last_seen_at: timestamp("last_seen_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
]);

export const ingredientsLibrary = pgTable("ingredients_library", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  name: text("name").notNull(),
  category: text("category"),
  calories_100g: doublePrecision("calories_100g").notNull(),
  protein_100g: doublePrecision("protein_100g"),
  carbs_100g: doublePrecision("carbs_100g"),
  fat_100g: doublePrecision("fat_100g"),
  image_url: text("image_url"),
  source: text("source").default("system"),
  barcode: text("barcode"),
  brands: text("brands"),
  micronutrients_json: jsonb("micronutrients_json"),
  data_license: text("data_license"),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  deleted_by: integer("deleted_by"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  original_name: text("original_name"),
  normalized_name: text("normalized_name"),
  aliases_json: jsonb("aliases_json").notNull().default(sql.raw("'[]'::jsonb")),
  search_keywords: text("search_keywords").notNull().default(""),
  preparation_state: text("preparation_state").notNull().default("unspecified"),
  quality_status: text("quality_status").notNull().default("trusted"),
  source_version: text("source_version"),
  source_updated_at: timestamp("source_updated_at", { withTimezone: true, mode: "string" }),
  nutrition_basis: text("nutrition_basis").notNull().default("per_100g"),
  edible_ratio: doublePrecision("edible_ratio").notNull().default(1),
  review_notes: text("review_notes"),
}, (table) => [
  index("idx_ingredients_library_barcode").on(table.barcode),
  index("idx_ingredients_library_deleted_at").on(table.deleted_at),
  index("idx_ingredients_normalized_quality").on(table.normalized_name, table.quality_status).where(sql.raw("deleted_at IS NULL")),
]);

export const inventoryChangeLogs = pgTable("inventory_change_logs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  inventory_item_id: integer("inventory_item_id").notNull().references((): AnyPgColumn => inventoryItems.id, { onDelete: "cascade" }),
  action: text("action").notNull(),
  source: text("source").notNull(),
  quantity_before: doublePrecision("quantity_before"),
  quantity_after: doublePrecision("quantity_after"),
  quantity_unit: text("quantity_unit"),
  delta_value: doublePrecision("delta_value"),
  idempotency_key: text("idempotency_key"),
  metadata_json: jsonb("metadata_json"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_inventory_change_logs_item").on(table.user_id, table.inventory_item_id, table.created_at.desc()),
  unique("inventory_change_logs_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
]);

export const inventoryConsumptionRequests = pgTable("inventory_consumption_requests", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("inventory_consumption_requests_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
]);

export const inventoryIntakeBatches = pgTable("inventory_intake_batches", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  source: text("source").notNull(),
  source_reference: text("source_reference"),
  confirmed_payload_json: jsonb("confirmed_payload_json").notNull(),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_inventory_intake_batches_user_created").on(table.user_id, table.created_at.desc()),
  unique("inventory_intake_batches_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
  check("inventory_intake_batches_check_1", sql.raw("source IN ('barcode', 'receipt', 'image', 'manual', 'recent')")),
]);

export const inventoryItems = pgTable("inventory_items", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  food_name: text("food_name").notNull(),
  category: text("category").notNull(),
  quantity: text("quantity").notNull(),
  expiration_date: text("expiration_date").notNull(),
  storage_location: text("storage_location").default("冷藏"),
  image_url: text("image_url"),
  is_available: boolean("is_available").default(true),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  quantity_value: doublePrecision("quantity_value"),
  quantity_unit: text("quantity_unit"),
  package_size_value: doublePrecision("package_size_value"),
  package_size_unit: text("package_size_unit"),
  batch_code: text("batch_code"),
  version: integer("version").notNull().default(1),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_inventory_batches_fefo").on(table.user_id, table.food_name, table.is_available, table.expiration_date, table.id),
]);

export const inventoryOutcomeEvents = pgTable("inventory_outcome_events", {
  id: text("id").primaryKey().notNull(),
  scope: text("scope").notNull(),
  user_id: integer("user_id").references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  household_id: integer("household_id").references((): AnyPgColumn => households.id, { onDelete: "cascade" }),
  inventory_item_id: integer("inventory_item_id").references((): AnyPgColumn => inventoryItems.id, { onDelete: "cascade" }),
  household_inventory_item_id: integer("household_inventory_item_id").references((): AnyPgColumn => householdInventoryItems.id, { onDelete: "cascade" }),
  outcome: text("outcome").notNull(),
  source: text("source").notNull(),
  quantity_value: doublePrecision("quantity_value"),
  quantity_unit: text("quantity_unit"),
  quantity_text: text("quantity_text"),
  idempotency_key: text("idempotency_key").notNull(),
  version: integer("version").notNull().default(1),
  occurred_at: timestamp("occurred_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  created_by_user_id: integer("created_by_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  updated_by_user_id: integer("updated_by_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_inventory_outcomes_household_week").on(table.household_id, table.occurred_at).where(sql.raw("scope = 'household'")),
  index("idx_inventory_outcomes_personal_week").on(table.user_id, table.occurred_at).where(sql.raw("scope = 'personal'")),
  unique("inventory_outcome_events_household_id_idempotency_key_key").on(table.household_id, table.idempotency_key),
  unique("inventory_outcome_events_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
  unique("inventory_outcome_events_created_by_user_id_idempotency_key_key").on(table.created_by_user_id, table.idempotency_key),
  check("inventory_outcome_events_check_1", sql.raw("scope IN ('personal', 'household')")),
  check("inventory_outcome_events_check_2", sql.raw("outcome IN ('cooked', 'used', 'discarded', 'expired', 'gifted', 'transferred', 'unknown')")),
  check("inventory_outcome_events_check_3", sql.raw("source IN ('manual', 'cooking', 'reminder', 'recommendation', 'cleanup')")),
  check("inventory_outcome_events_check_4", sql.raw("(scope = 'personal' AND user_id IS NOT NULL AND inventory_item_id IS NOT NULL AND household_id IS NULL AND household_inventory_item_id IS NULL)\n             OR (scope = 'household' AND household_id IS NOT NULL AND household_inventory_item_id IS NOT NULL AND user_id IS NULL AND inventory_item_id IS NULL)")),
]);

export const inventoryScanJobs = pgTable("inventory_scan_jobs", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  image_hash: text("image_hash").notNull(),
  status: text("status").notNull().default("queued"),
  result_json: jsonb("result_json"),
  error_message: text("error_message"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  index("idx_inventory_scan_jobs_user_status").on(table.user_id, table.status, table.updated_at.desc()),
  index("idx_inventory_scan_jobs_user_hash").on(table.user_id, table.image_hash, table.created_at.desc()),
]);

export const kitchenwareCapabilities = pgTable("kitchenware_capabilities", {
  code: text("code").primaryKey().notNull(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  safety_level: text("safety_level").notNull().default("normal"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("kitchenware_capabilities_name_key").on(table.name),
  check("kitchenware_capabilities_check_1", sql.raw("safety_level IN ('normal', 'caution', 'restricted')")),
]);

export const kitchenwareCatalog = pgTable("kitchenware_catalog", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  name: text("name").notNull(),
  category: text("category").notNull(),
  aliases: jsonb("aliases").default(sql.raw("'[]'::jsonb")),
  cooking_methods: jsonb("cooking_methods").default(sql.raw("'[]'::jsonb")),
  care_note: text("care_note"),
  source: text("source").default("system"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  attributes_json: jsonb("attributes_json").notNull().default(sql.raw("'{}'::jsonb")),
  quality_status: text("quality_status").notNull().default("trusted"),
  capability_version: integer("capability_version").notNull().default(1),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  unique("kitchenware_catalog_name_key").on(table.name),
]);

export const kitchenwareCatalogCapabilities = pgTable("kitchenware_catalog_capabilities", {
  catalog_id: integer("catalog_id").notNull().references((): AnyPgColumn => kitchenwareCatalog.id, { onDelete: "cascade" }),
  capability_code: text("capability_code").notNull().references((): AnyPgColumn => kitchenwareCapabilities.code, { onDelete: "cascade" }),
  constraints_json: jsonb("constraints_json").notNull().default(sql.raw("'{}'::jsonb")),
}, (table) => [
  primaryKey({ name: "kitchenware_catalog_capabilities_pkey", columns: [table.catalog_id, table.capability_code] }),
]);

export const kitchenwareItems = pgTable("kitchenware_items", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  original_name: text("original_name"),
  category: text("category").notNull(),
  status: text("status").default("良好"),
  note: text("note"),
  image_url: text("image_url"),
  purchase_date: text("purchase_date"),
  last_maintained_at: timestamp("last_maintained_at", { withTimezone: true, mode: "string" }),
  usage_count: integer("usage_count").default(0),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  deleted_by: integer("deleted_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  ip_location: text("ip_location"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  catalog_id: integer("catalog_id"),
  attributes_json: jsonb("attributes_json").notNull().default(sql.raw("'{}'::jsonb")),
}, (table) => [
  index("idx_kitchenware_deleted_at").on(table.deleted_at),
  index("idx_kitchenware_user_created_at").on(table.user_id, table.created_at),
]);

export const kitchenwareMappingReviews = pgTable("kitchenware_mapping_reviews", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  raw_name: text("raw_name").notNull(),
  normalized_name: text("normalized_name").notNull(),
  source_type: text("source_type").notNull(),
  source_id: text("source_id"),
  confidence: doublePrecision("confidence").notNull().default(0),
  suggested_catalog_id: integer("suggested_catalog_id").references((): AnyPgColumn => kitchenwareCatalog.id, { onDelete: "set null" }),
  status: text("status").notNull().default("pending"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  reviewed_at: timestamp("reviewed_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  unique("kitchenware_mapping_reviews_normalized_name_source_type_source_id_key").on(table.normalized_name, table.source_type, table.source_id),
  check("kitchenware_mapping_reviews_check_1", sql.raw("status IN ('pending', 'approved', 'rejected')")),
]);

export const kitchenwareSubstitutions = pgTable("kitchenware_substitutions", {
  source_catalog_id: integer("source_catalog_id").notNull().references((): AnyPgColumn => kitchenwareCatalog.id, { onDelete: "cascade" }),
  substitute_catalog_id: integer("substitute_catalog_id").notNull().references((): AnyPgColumn => kitchenwareCatalog.id, { onDelete: "cascade" }),
  relation_type: text("relation_type").notNull(),
  impact_json: jsonb("impact_json").notNull().default(sql.raw("'{}'::jsonb")),
  safety_note: text("safety_note").notNull().default(""),
}, (table) => [
  primaryKey({ name: "kitchenware_substitutions_pkey", columns: [table.source_catalog_id, table.substitute_catalog_id] }),
  check("kitchenware_substitutions_check_1", sql.raw("relation_type IN ('equivalent', 'conditional', 'forbidden')")),
]);

export const mealPlanExecutionRequests = pgTable("meal_plan_execution_requests", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  action: text("action").notNull(),
  meal_plan_item_id: text("meal_plan_item_id").notNull().references((): AnyPgColumn => mealPlanItems.id, { onDelete: "cascade" }),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("meal_plan_execution_requests_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
]);

export const mealPlanItems = pgTable("meal_plan_items", {
  id: text("id").primaryKey().notNull(),
  plan_id: text("plan_id").notNull().references((): AnyPgColumn => mealPlans.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  planned_date: text("planned_date").notNull(),
  meal_type: text("meal_type").notNull(),
  title: text("title").notNull(),
  recipe_id: integer("recipe_id").references((): AnyPgColumn => recipes.id, { onDelete: "set null" }),
  ingredients_json: jsonb("ingredients_json").notNull().default(sql.raw("'[]'::jsonb")),
  steps_json: jsonb("steps_json").notNull().default(sql.raw("'[]'::jsonb")),
  calories: doublePrecision("calories"),
  protein: doublePrecision("protein"),
  carbs: doublePrecision("carbs"),
  fat: doublePrecision("fat"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("planned"),
  diet_record_id: integer("diet_record_id").references((): AnyPgColumn => dietRecords.id, { onDelete: "set null" }),
  queue_item_id: text("queue_item_id").references((): AnyPgColumn => cookingQueueItems.id, { onDelete: "set null" }),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  index("idx_meal_plan_items_execution").on(table.user_id, table.planned_date, table.status).where(sql.raw("deleted_at IS NULL")),
  index("idx_meal_plan_items_user_date").on(table.user_id, table.planned_date, table.meal_type),
  check("meal_plan_items_check_1", sql.raw("status IN ('planned', 'queued', 'cooking', 'completed', 'skipped')")),
]);

export const mealPlans = pgTable("meal_plans", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  start_date: text("start_date").notNull(),
  end_date: text("end_date").notNull(),
  status: text("status").notNull().default("active"),
  source: text("source").notNull().default("agent"),
  constraints_json: jsonb("constraints_json").notNull().default(sql.raw("'{}'::jsonb")),
  created_by_run_id: text("created_by_run_id").references((): AnyPgColumn => agentRuns.id, { onDelete: "set null" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  version: integer("version").notNull().default(1),
}, (table) => [
  index("idx_meal_plans_user_dates").on(table.user_id, table.start_date, table.end_date),
  check("meal_plans_check_1", sql.raw("status IN ('draft', 'active', 'completed', 'cancelled')")),
]);

export const mediaCleanupJobs = pgTable("media_cleanup_jobs", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  owner_user_id: integer("owner_user_id").notNull(),
  urls_json: jsonb("urls_json").notNull(),
  status: text("status").notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  last_error: text("last_error"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  claim_token: text("claim_token"),
  claimed_at: timestamp("claimed_at", { withTimezone: true, mode: "string" }),
  objects_json: jsonb("objects_json"),
}, (table) => [
  index("idx_media_cleanup_jobs_claim").on(table.status, table.claimed_at, table.created_at, table.id),
  index("idx_media_cleanup_jobs_status_created").on(table.status, table.created_at, table.id),
  check("media_cleanup_jobs_check_1", sql.raw("status IN ('pending', 'processing', 'completed')")),
]);

export const notificationCampaignDeliveries = pgTable("notification_campaign_deliveries", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  campaign_id: integer("campaign_id").notNull().references((): AnyPgColumn => notificationCampaigns.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  push_device_id: integer("push_device_id").notNull().references((): AnyPgColumn => pushDevices.id, { onDelete: "cascade" }),
  status: text("status").notNull(),
  error_code: text("error_code"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_notification_deliveries_campaign").on(table.campaign_id, table.status),
]);

export const notificationCampaigns = pgTable("notification_campaigns", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  admin_user_id: integer("admin_user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  body: text("body").notNull(),
  status: text("status").notNull().default("sending"),
  recipient_count: integer("recipient_count").notNull().default(0),
  success_count: integer("success_count").notNull().default(0),
  failure_count: integer("failure_count").notNull().default(0),
  sent_at: timestamp("sent_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_notification_campaigns_created").on(table.created_at.desc()),
]);

export const notificationDeliveries = pgTable("notification_deliveries", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  inventory_item_id: integer("inventory_item_id").references((): AnyPgColumn => inventoryItems.id, { onDelete: "cascade" }),
  notification_type: text("notification_type").notNull(),
  delivery_date: text("delivery_date").notNull(),
  status: text("status").notNull().default("queued"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("notification_deliveries_user_id_inventory_item_id_notification_type_delivery_date_key").on(table.user_id, table.inventory_item_id, table.notification_type, table.delivery_date),
]);

export const notificationEvents = pgTable("notification_events", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  notification_id: integer("notification_id").references((): AnyPgColumn => userNotificationInbox.id, { onDelete: "set null" }),
  event_type: text("event_type").notNull(),
  metadata_json: jsonb("metadata_json"),
  expo_ticket_id: text("expo_ticket_id"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_notification_events_ticket").on(table.expo_ticket_id),
  index("idx_notification_events_notification_created").on(table.notification_id, table.created_at.desc()),
]);

export const notificationInventoryItems = pgTable("notification_inventory_items", {
  notification_id: integer("notification_id").notNull().references((): AnyPgColumn => userNotificationInbox.id, { onDelete: "cascade" }),
  inventory_item_id: integer("inventory_item_id").notNull().references((): AnyPgColumn => inventoryItems.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ name: "notification_inventory_items_pkey", columns: [table.notification_id, table.inventory_item_id] }),
  index("idx_notification_inventory_items_user").on(table.user_id, table.notification_id),
]);

export const pushDevices = pgTable("push_devices", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  expo_push_token: text("expo_push_token").notNull(),
  platform: text("platform").notNull(),
  is_active: boolean("is_active").notNull().default(true),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_push_devices_user_active").on(table.user_id, table.is_active),
  unique("push_devices_expo_push_token_key").on(table.expo_push_token),
]);

export const pushNotificationReceipts = pgTable("push_notification_receipts", {
  expo_ticket_id: text("expo_ticket_id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  notification_id: integer("notification_id").references((): AnyPgColumn => userNotificationInbox.id, { onDelete: "set null" }),
  expo_push_token: text("expo_push_token").notNull(),
  submit_status: text("submit_status").notNull(),
  receipt_status: text("receipt_status").notNull().default("pending"),
  error_code: text("error_code"),
  error_message: text("error_message"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  checked_at: timestamp("checked_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  index("idx_push_receipts_pending").on(table.receipt_status, table.created_at),
]);

export const rateLimitBuckets = pgTable("rate_limit_buckets", {
  bucket_key: text("bucket_key").primaryKey().notNull(),
  request_count: integer("request_count").notNull().default(0),
  window_started_at: bigint("window_started_at", { mode: "number" }).notNull(),
  blocked_until: bigint("blocked_until", { mode: "number" }).notNull().default(sql.raw("0")),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_rate_limit_buckets_updated").on(table.updated_at),
]);

export const realtimeVoiceEvents = pgTable("realtime_voice_events", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  session_id: text("session_id").notNull().references((): AnyPgColumn => realtimeVoiceSessions.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  event_type: text("event_type").notNull(),
  payload_json: jsonb("payload_json").notNull().default(sql.raw("'{}'::jsonb")),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_realtime_voice_events_session_sequence").on(table.session_id, table.sequence),
  unique("realtime_voice_events_session_id_sequence_key").on(table.session_id, table.sequence),
]);

export const realtimeVoiceSessions = pgTable("realtime_voice_sessions", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("active"),
  client_platform: text("client_platform").notNull(),
  context_json: jsonb("context_json").notNull(),
  idempotency_key: text("idempotency_key").notNull(),
  version: integer("version").notNull().default(1),
  connected_at: timestamp("connected_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  last_heartbeat_at: timestamp("last_heartbeat_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  closed_at: timestamp("closed_at", { withTimezone: true, mode: "string" }),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }).notNull(),
  first_transcript_ms: integer("first_transcript_ms"),
  first_response_ms: integer("first_response_ms"),
  interruption_count: integer("interruption_count").notNull().default(0),
  reconnect_count: integer("reconnect_count").notNull().default(0),
  fallback_count: integer("fallback_count").notNull().default(0),
}, (table) => [
  unique("realtime_voice_sessions_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
  check("realtime_voice_sessions_check_1", sql.raw("status IN ('active', 'muted', 'closed', 'expired', 'fallback')")),
]);

export const realtimeVoiceTranscriptChunks = pgTable("realtime_voice_transcript_chunks", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  session_id: text("session_id").notNull().references((): AnyPgColumn => realtimeVoiceSessions.id, { onDelete: "cascade" }),
  turn_id: text("turn_id").notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  transcript: text("transcript").notNull().default(""),
  is_final: boolean("is_final").notNull().default(false),
  audio_bytes: integer("audio_bytes").notNull().default(0),
  latency_ms: integer("latency_ms").notNull().default(0),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_realtime_voice_chunks_turn_sequence").on(table.session_id, table.turn_id, table.sequence),
  unique("realtime_voice_transcript_chunks_session_id_turn_id_sequence_key").on(table.session_id, table.turn_id, table.sequence),
]);

export const realtimeVoiceTurns = pgTable("realtime_voice_turns", {
  id: text("id").primaryKey().notNull(),
  session_id: text("session_id").notNull().references((): AnyPgColumn => realtimeVoiceSessions.id, { onDelete: "cascade" }),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  transcript: text("transcript").notNull(),
  intent: text("intent").notNull(),
  action_json: jsonb("action_json").notNull().default(sql.raw("'{}'::jsonb")),
  agent_run_id: text("agent_run_id"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("realtime_voice_turns_session_id_id_key").on(table.session_id, table.id),
]);

export const recipeCoverageBaselines = pgTable("recipe_coverage_baselines", {
  dimension: text("dimension").notNull(),
  value: text("value").notNull(),
  minimum_candidates: integer("minimum_candidates").notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ name: "recipe_coverage_baselines_pkey", columns: [table.dimension, table.value] }),
  check("recipe_coverage_baselines_check_1", sql.raw("minimum_candidates >= 0")),
]);

export const recipeDuplicateCandidates = pgTable("recipe_duplicate_candidates", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  candidate_recipe_id: integer("candidate_recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  similarity: doublePrecision("similarity").notNull(),
  reasons_json: jsonb("reasons_json").notNull().default(sql.raw("'[]'::jsonb")),
  status: text("status").notNull().default("pending"),
  reviewed_by: integer("reviewed_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  reviewed_at: timestamp("reviewed_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("recipe_duplicate_candidates_recipe_id_candidate_recipe_id_key").on(table.recipe_id, table.candidate_recipe_id),
  check("recipe_duplicate_candidates_check_1", sql.raw("similarity >= 0 AND similarity <= 1")),
  check("recipe_duplicate_candidates_check_2", sql.raw("status IN ('pending', 'merged', 'distinct', 'dismissed')")),
  check("recipe_duplicate_candidates_check_3", sql.raw("recipe_id < candidate_recipe_id")),
]);

export const recipeFavorites = pgTable("recipe_favorites", {
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  primaryKey({ name: "recipe_favorites_pkey", columns: [table.user_id, table.recipe_id] }),
  index("idx_recipe_favorites_user_created").on(table.user_id, table.created_at.desc()),
]);

export const recipeImportBatchItems = pgTable("recipe_import_batch_items", {
  batch_id: text("batch_id").notNull().references((): AnyPgColumn => recipeImportBatches.id, { onDelete: "cascade" }),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  action: text("action").notNull(),
  before_json: jsonb("before_json"),
  after_json: jsonb("after_json").notNull(),
}, (table) => [
  primaryKey({ name: "recipe_import_batch_items_pkey", columns: [table.batch_id, table.recipe_id] }),
  check("recipe_import_batch_items_check_1", sql.raw("action IN ('insert', 'update')")),
]);

export const recipeImportBatches = pgTable("recipe_import_batches", {
  id: text("id").primaryKey().notNull(),
  source: text("source").notNull(),
  source_revision: text("source_revision").notNull(),
  data_license: text("data_license").notNull(),
  status: text("status").notNull(),
  stats_json: jsonb("stats_json").notNull().default(sql.raw("'{}'::jsonb")),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  completed_at: timestamp("completed_at", { withTimezone: true, mode: "string" }),
  rolled_back_at: timestamp("rolled_back_at", { withTimezone: true, mode: "string" }),
  error_json: jsonb("error_json"),
}, (table) => [
  check("recipe_import_batches_check_1", sql.raw("status IN ('running', 'validated', 'committed', 'rolled_back', 'failed')")),
]);

export const recipeKitchenwareRequirements = pgTable("recipe_kitchenware_requirements", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  catalog_id: integer("catalog_id").references((): AnyPgColumn => kitchenwareCatalog.id, { onDelete: "cascade" }),
  capability_code: text("capability_code").references((): AnyPgColumn => kitchenwareCapabilities.code, { onDelete: "cascade" }),
  role: text("role").notNull(),
  source: text("source").notNull().default("curated"),
  confidence: doublePrecision("confidence").notNull().default(1),
  notes: text("notes").notNull().default(""),
}, (table) => [
  index("idx_recipe_requirements_recipe_role").on(table.recipe_id, table.role),
  unique("recipe_kitchenware_requirements_recipe_id_catalog_id_capability_code_role_key").on(table.recipe_id, table.catalog_id, table.capability_code, table.role),
  check("recipe_kitchenware_requirements_check_1", sql.raw("role IN ('required', 'optional', 'convenience')")),
  check("recipe_kitchenware_requirements_check_2", sql.raw("confidence >= 0 AND confidence <= 1")),
  check("recipe_kitchenware_requirements_check_3", sql.raw("catalog_id IS NOT NULL OR capability_code IS NOT NULL")),
]);

export const recipeRecommendationEvents = pgTable("recipe_recommendation_events", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  request_id: text("request_id").references((): AnyPgColumn => recipeRecommendationRequests.id, { onDelete: "set null" }),
  recipe_id: integer("recipe_id").notNull().references((): AnyPgColumn => recipes.id, { onDelete: "cascade" }),
  event_type: text("event_type").notNull(),
  scoring_version: text("scoring_version").notNull(),
  surface: text("surface").notNull(),
  metadata_json: jsonb("metadata_json").notNull().default(sql.raw("'{}'::jsonb")),
  idempotency_key: text("idempotency_key").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_recipe_recommendation_events_user_recipe").on(table.user_id, table.recipe_id, table.created_at.desc()),
  unique("recipe_recommendation_events_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
  check("recipe_recommendation_events_check_1", sql.raw("event_type IN ('exposure', 'view', 'favorite', 'skip', 'shopping', 'queue', 'start', 'complete', 'constraint_change')")),
]);

export const recipeRecommendationRequests = pgTable("recipe_recommendation_requests", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  surface: text("surface").notNull(),
  scoring_version: text("scoring_version").notNull(),
  candidate_version: text("candidate_version").notNull(),
  input_hash: text("input_hash").notNull(),
  input_snapshot_json: jsonb("input_snapshot_json").notNull(),
  results_json: jsonb("results_json").notNull(),
  data_updated_at: timestamp("data_updated_at", { withTimezone: true, mode: "string" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  expires_at: timestamp("expires_at", { withTimezone: true, mode: "string" }).notNull(),
}, (table) => [
  index("idx_recipe_recommendation_requests_user_created").on(table.user_id, table.created_at.desc()),
]);

export const recipes = pgTable("recipes", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  title: text("title").notNull(),
  description: text("description"),
  image_url: text("image_url"),
  cook_time: integer("cook_time"),
  difficulty: text("difficulty"),
  calories: integer("calories"),
  protein: doublePrecision("protein"),
  carbs: doublePrecision("carbs"),
  fat: doublePrecision("fat"),
  nutrition_json: jsonb("nutrition_json"),
  category: text("category"),
  tags: jsonb("tags"),
  steps_json: jsonb("steps_json"),
  ingredients_json: jsonb("ingredients_json"),
  author_user_id: integer("author_user_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  source: text("source").default("official"),
  status: text("status").default("approved"),
  reviewed_by: integer("reviewed_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  reviewed_at: timestamp("reviewed_at", { withTimezone: true, mode: "string" }),
  reject_reason: text("reject_reason"),
  external_id: text("external_id"),
  source_url: text("source_url"),
  data_license: text("data_license"),
  source_revision: text("source_revision"),
  source_attribution: text("source_attribution"),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
  deleted_by: integer("deleted_by"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  quality_status: text("quality_status").notNull().default("trusted"),
  nutrition_basis: text("nutrition_basis").notNull().default("source"),
  quality_issues_json: jsonb("quality_issues_json").notNull().default(sql.raw("'[]'::jsonb")),
  quality_reviewed_by: integer("quality_reviewed_by"),
  quality_reviewed_at: timestamp("quality_reviewed_at", { withTimezone: true, mode: "string" }),
  quality_review_reason: text("quality_review_reason"),
  canonical_key: text("canonical_key"),
  source_content_hash: text("source_content_hash"),
  import_batch_id: text("import_batch_id"),
  serving_size: integer("serving_size"),
  prep_time: integer("prep_time"),
  cuisine: text("cuisine"),
  meal_types_json: jsonb("meal_types_json").notNull().default(sql.raw("'[]'::jsonb")),
  required_kitchenware_json: jsonb("required_kitchenware_json").notNull().default(sql.raw("'[]'::jsonb")),
  optional_kitchenware_json: jsonb("optional_kitchenware_json").notNull().default(sql.raw("'[]'::jsonb")),
  duplicate_of_recipe_id: integer("duplicate_of_recipe_id"),
  withdrawn_at: timestamp("withdrawn_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  uniqueIndex("idx_recipes_source_external_id").on(table.source, table.external_id).where(sql.raw("external_id IS NOT NULL")),
  index("idx_recipes_author_created_at").on(table.author_user_id, table.created_at),
  index("idx_recipes_status_source").on(table.status, table.source, table.deleted_at),
  index("idx_recipes_deleted_at").on(table.deleted_at),
  index("idx_recipes_canonical_quality").on(table.canonical_key, table.quality_status).where(sql.raw("deleted_at IS NULL")),
  index("idx_recipes_quality_review").on(table.quality_status, table.source, table.id.desc()).where(sql.raw("deleted_at IS NULL")),
  index("idx_recipes_public_quality").on(table.status, table.quality_status, table.id.desc()).where(sql.raw("deleted_at IS NULL")),
]);

export const schemaMigrations = pgTable("schema_migrations", {
  version: integer("version").primaryKey().notNull(),
  name: text("name").notNull(),
  applied_at: timestamp("applied_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
]);

export const shoppingInventoryImports = pgTable("shopping_inventory_imports", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  idempotency_key: text("idempotency_key").notNull(),
  result_json: jsonb("result_json").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  unique("shopping_inventory_imports_user_id_idempotency_key_key").on(table.user_id, table.idempotency_key),
]);

export const shoppingListItems = pgTable("shopping_list_items", {
  id: text("id").primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  client_id: text("client_id"),
  name: text("name").notNull(),
  amount: text("amount").notNull().default("适量"),
  category: text("category").notNull().default("其他"),
  checked: boolean("checked").notNull().default(false),
  purchase_date: text("purchase_date"),
  storage_location: text("storage_location"),
  source_run_id: text("source_run_id").references((): AnyPgColumn => agentRuns.id, { onDelete: "set null" }),
  version: integer("version").notNull().default(1),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  index("idx_shopping_items_user_active").on(table.user_id, table.checked, table.updated_at.desc()).where(sql.raw("deleted_at IS NULL")),
  uniqueIndex("idx_shopping_items_user_client").on(table.user_id, table.client_id).where(sql.raw("client_id IS NOT NULL")),
]);

export const systemSettings = pgTable("system_settings", {
  key: text("key").primaryKey().notNull(),
  value: text("value").notNull(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
]);

export const userCustomFoods = pgTable("user_custom_foods", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  calories_100g: doublePrecision("calories_100g").notNull(),
  protein_100g: doublePrecision("protein_100g").default(0),
  carbs_100g: doublePrecision("carbs_100g").default(0),
  fat_100g: doublePrecision("fat_100g").default(0),
  category: text("category").default("自定义"),
  image_url: text("image_url"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  status: text("status").notNull().default("pending"),
}, (table) => [
  index("idx_user_custom_foods_status_created").on(table.status, table.created_at.desc()),
]);

export const userDailyCheckIns = pgTable("user_daily_check_ins", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  check_in_date: text("check_in_date").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_user_daily_check_ins_user_date").on(table.user_id, table.check_in_date.desc()),
  unique("user_daily_check_ins_user_id_check_in_date_key").on(table.user_id, table.check_in_date),
]);

export const userFeedback = pgTable("user_feedback", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  category: text("category").notNull(),
  content: text("content").notNull(),
  context_json: jsonb("context_json"),
  status: text("status").notNull().default("open"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  index("idx_user_feedback_user_created").on(table.user_id, table.created_at.desc()),
  check("user_feedback_check_1", sql.raw("category IN ('issue', 'suggestion', 'support')")),
]);

export const userFollows = pgTable("user_follows", {
  follower_id: integer("follower_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  following_id: integer("following_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ name: "user_follows_pkey", columns: [table.follower_id, table.following_id] }),
  index("idx_user_follows_follower_created").on(table.follower_id, table.created_at.desc()),
  check("user_follows_check_1", sql.raw("follower_id != following_id")),
]);

export const userHealthProfiles = pgTable("user_health_profiles", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  gender: text("gender").default("保密"),
  age: integer("age"),
  height: doublePrecision("height"),
  weight: doublePrecision("weight"),
  target_weight: doublePrecision("target_weight"),
  health_goal: text("health_goal").default("healthy"),
  activity_level: text("activity_level").default("moderate"),
  dietary_preference: text("dietary_preference").default("无特别偏好"),
  allergies_json: jsonb("allergies_json").default(sql.raw("'[]'::jsonb")),
  medications: text("medications").default(""),
  medical_conditions_json: jsonb("medical_conditions_json").default(sql.raw("'[]'::jsonb")),
  medical_notes: text("medical_notes").default(""),
  dietary_restrictions_json: jsonb("dietary_restrictions_json").default(sql.raw("'[]'::jsonb")),
  disliked_foods: text("disliked_foods").default(""),
  kitchen_constraints_json: jsonb("kitchen_constraints_json").default(sql.raw("'{}'::jsonb")),
  nutrition_targets_json: jsonb("nutrition_targets_json").default(sql.raw("'{}'::jsonb")),
  tracking_enabled: boolean("tracking_enabled").default(false),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).defaultNow(),
}, (table) => [
  unique("user_health_profiles_user_id_key").on(table.user_id),
]);

export const userLevelAdjustments = pgTable("user_level_adjustments", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  admin_user_id: integer("admin_user_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  xp_delta: integer("xp_delta").notNull(),
  reason: text("reason").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_user_level_adjustments_user_created").on(table.user_id, table.created_at.desc()),
  check("user_level_adjustments_check_1", sql.raw("xp_delta != 0")),
]);

export const userNotificationInbox = pgTable("user_notification_inbox", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  user_id: integer("user_id").notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  type: text("type").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  campaign_id: integer("campaign_id").references((): AnyPgColumn => notificationCampaigns.id, { onDelete: "cascade" }),
  inventory_item_id: integer("inventory_item_id").references((): AnyPgColumn => inventoryItems.id, { onDelete: "cascade" }),
  is_read: boolean("is_read").notNull().default(false),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  category: text("category").notNull().default("action_required"),
  priority: text("priority").notNull().default("normal"),
  action_status: text("action_status").notNull().default("pending"),
  group_key: text("group_key"),
  read_at: timestamp("read_at", { withTimezone: true, mode: "string" }),
  snoozed_until: timestamp("snoozed_until", { withTimezone: true, mode: "string" }),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_user_notification_inbox_filter").on(table.user_id, table.category, table.action_status, table.id.desc()),
  index("idx_user_notification_inbox_unread").on(table.user_id, table.is_read, table.id.desc()),
  index("idx_user_notification_inbox_user_created").on(table.user_id, table.created_at.desc()),
  unique("user_notification_inbox_user_id_campaign_id_key").on(table.user_id, table.campaign_id),
]);

export const userNotificationPreferences = pgTable("user_notification_preferences", {
  user_id: integer("user_id").primaryKey().notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  expiring_alert: boolean("expiring_alert").notNull().default(true),
  meal_reminder: boolean("meal_reminder").notNull().default(true),
  water_reminder: boolean("water_reminder").notNull().default(true),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  breakfast_time: text("breakfast_time").notNull().default("08:00"),
  lunch_time: text("lunch_time").notNull().default("12:00"),
  dinner_time: text("dinner_time").notNull().default("18:00"),
  water_start_time: text("water_start_time").notNull().default("10:00"),
  water_end_time: text("water_end_time").notNull().default("18:00"),
  water_interval_minutes: integer("water_interval_minutes").notNull().default(120),
  quiet_start_time: text("quiet_start_time").notNull().default("22:00"),
  quiet_end_time: text("quiet_end_time").notNull().default("07:00"),
  weekdays_enabled: boolean("weekdays_enabled").notNull().default(true),
  weekends_enabled: boolean("weekends_enabled").notNull().default(true),
}, (table) => [
]);

export const userVoicePreferences = pgTable("user_voice_preferences", {
  user_id: integer("user_id").primaryKey().notNull().references((): AnyPgColumn => users.id, { onDelete: "cascade" }),
  selected_voice_id: text("selected_voice_id"),
  selected_version: text("selected_version"),
  preference: text("preference").notNull().default("automatic"),
  version: integer("version").notNull().default(1),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  check("user_voice_preferences_check_1", sql.raw("preference IN ('automatic', 'system-only')")),
]);

export const users = pgTable("users", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  username: text("username").notNull(),
  email: text("email"),
  phone: text("phone"),
  password_hash: text("password_hash").notNull(),
  nickname: text("nickname"),
  avatar_url: text("avatar_url"),
  bio: text("bio"),
  role: text("role").default("user"),
  must_change_password: boolean("must_change_password").default(false),
  session_version: integer("session_version").notNull().default(1),
  daily_calories_target: integer("daily_calories_target").default(2000),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).defaultNow(),
  last_login_at: timestamp("last_login_at", { withTimezone: true, mode: "string" }),
  last_login_ip: text("last_login_ip"),
  is_verified_expert: boolean("is_verified_expert").default(false),
  is_disabled: boolean("is_disabled").default(false),
  phone_verified_at: timestamp("phone_verified_at", { withTimezone: true, mode: "string" }),
}, (table) => [
  uniqueIndex("idx_users_phone_unique").on(table.phone).where(sql.raw("phone IS NOT NULL")),
  uniqueIndex("idx_users_email_unique").on(table.email).where(sql.raw("email IS NOT NULL")),
  unique("users_phone_key").on(table.phone),
  unique("users_email_key").on(table.email),
  unique("users_username_key").on(table.username),
]);

export const voicePackStatusHistory = pgTable("voice_pack_status_history", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  voice_pack_version_id: integer("voice_pack_version_id").notNull().references((): AnyPgColumn => voicePackVersions.id, { onDelete: "cascade" }),
  actor_user_id: integer("actor_user_id").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  from_status: text("from_status"),
  to_status: text("to_status").notNull(),
  reason: text("reason"),
  revision: integer("revision").notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_voice_pack_history_version_created").on(table.voice_pack_version_id, table.created_at.desc(), table.id.desc()),
]);

export const voicePackVersions = pgTable("voice_pack_versions", {
  id: integer("id").generatedByDefaultAsIdentity().primaryKey().notNull(),
  voice_id: text("voice_id").notNull(),
  name: text("name").notNull(),
  version: text("version").notNull(),
  language: text("language").notNull().default("zh-CN"),
  style_tags_json: jsonb("style_tags_json").notNull().default(sql.raw("'[]'::jsonb")),
  manifest_json: jsonb("manifest_json").notNull(),
  resource_fingerprint: text("resource_fingerprint").notNull(),
  provider_voice: text("provider_voice"),
  status: text("status").notNull().default("draft"),
  revision: integer("revision").notNull().default(1),
  created_by: integer("created_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  reviewed_by: integer("reviewed_by").references((): AnyPgColumn => users.id, { onDelete: "set null" }),
  published_at: timestamp("published_at", { withTimezone: true, mode: "string" }),
  revoked_at: timestamp("revoked_at", { withTimezone: true, mode: "string" }),
  revoke_reason: text("revoke_reason"),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
  index("idx_voice_pack_versions_status_voice").on(table.status, table.voice_id, table.version),
  unique("voice_pack_versions_voice_id_version_key").on(table.voice_id, table.version),
  unique("voice_pack_versions_resource_fingerprint_key").on(table.resource_fingerprint),
  check("voice_pack_versions_check_1", sql.raw("status IN ('draft', 'published', 'disabled', 'revoked')")),
]);

export const workerTaskLeases = pgTable("worker_task_leases", {
  task_name: text("task_name").primaryKey().notNull(),
  owner_id: text("owner_id").notNull(),
  lease_expires_at: timestamp("lease_expires_at", { withTimezone: true, mode: "string" }).notNull(),
  created_at: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
}, (table) => [
]);

export const workerTaskRuns = pgTable("worker_task_runs", {
  id: text("id").primaryKey().notNull(),
  task_name: text("task_name").notNull(),
  worker_id: text("worker_id").notNull(),
  status: text("status").notNull(),
  started_at: timestamp("started_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  finished_at: timestamp("finished_at", { withTimezone: true, mode: "string" }),
  duration_ms: integer("duration_ms"),
  processed_count: integer("processed_count").notNull().default(0),
  succeeded_count: integer("succeeded_count").notNull().default(0),
  failed_count: integer("failed_count").notNull().default(0),
  result_json: jsonb("result_json"),
  error_message: text("error_message"),
}, (table) => [
  index("idx_worker_task_runs_status_started").on(table.status, table.started_at.desc(), table.id.desc()),
  index("idx_worker_task_runs_task_started").on(table.task_name, table.started_at.desc(), table.id.desc()),
  check("worker_task_runs_check_1", sql.raw("status IN ('running', 'completed', 'failed')")),
]);

